// ==UserScript==
// @include http://sg.hu/*
// @include https://sg.hu/*
// @include http://www.sg.hu/*
// @include https://www.sg.hu/*
// @include http://*.sg.hu/*
// @include https://*.sg.hu/*
// ==/UserScript==

window.valami = function() {
	alert('alert');
};

var cp = {

	init : function(page) {
		
		var iconImg		= "iVBORw0KGgoAAAANSUhEUgAAABwAAAAdCAYAAAC5UQwxAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABXpJREFUeNq0VmlIXFcUnhnH0XFX1KpYC+4bjlstWiVitNikhkJk3MdoXCtWSNQiAZcaScX8UFBiQtIMFReIaRtoJKgJ6g/3UaupW3ChWrWOGpe6j2O/K++F0XmmkSYPDvfdc+8792zfdx/78PCQdZZHKBR6Y7gE4UGeQZrO8j37LAeGhYWdw9ByQh0HEb+rDc5ZvOPz+VcZdHFnscFlUoaHh5OUXYTU19XVvUmZhobGRzs7O8f2qqqqGpzQeUBiIANMkSulNCIi4iaGGwqq65AXkCwVFZWvDg4OdI6liMPZlsvlpJblEANIHUSFWq6BiCAHjAdGRkaShmhnvccHDiXCofuMNTQyMvoMG1jvU/T19b0V58dqGBIS0lVTU7Oxv7+vrVRsLnfb3d29PigoSGJvb/+a6Kanp7Wbmppcu7q6Lu/u7uor1YvNlvn4+LQ0NDSwSCYxV6ohHwYyamtrc2UyGZ9WmpiYSFJSUu6JxWKjmZmZINTRi+AQHnchKy0JCQlT1dXVUXDAX+EweXBwcBl6okgkEi2f2jR3794VdHR09EJ/FL2ZmVlXcnJyYUFBwXeohR8jmNnsP2JjY3Px3dWxsbELtN7R0VE4PDz86K047Ovri4EBLsk3j8fbxGEFhYWF32LJ77Q6Yb9TVVXV93FxcUWampp/0/qpqalwpb0kwvj4eIK7VNI3UNohEi1yuI2NzROk8CFw9ivtkKGh4ZCnp+dz7JP39PScl0qlAnoNsLkmEAjs4XQSFfku7L/E6z8UJsVc5N8OG+uxoKrQykejhYXF47m5uSv0XE9PbxzRXldTUxvF9DA0NPRpdnZ22crKijNFAknOzs4JAwMDSZQpNRzqQb0TWvyTAyMEe6pHHXRC1NXVuzE60HNLS8vfcFhzYmKiKUQAeWFtbf2EXkczWfr7+/fBQRmTPR0dnYtcAwMD/sbGBiNoJyYmdgAHNh3h4uLiGonMw8PjEMblg4ODrIWFhWV6HZmSoeZ7mHOYLgVdXV01DurRg1RsM3m0vLxsh02v6PnS0tIVwEMXMpqWlkai58OJb+h1bW3tGdj6hFTlpC1ScwcHh1bSNHyJRJLa2tp6fm9vTwMGnNAkRsQjpLTKz8/veXNz84/Yx6EaYRrvP1H8GAmxoyOA87eGhoZ2QAIFVE03TE1NJSTFWGsPCAgoo3FICNmG7CkvL08dGRkR0V3m7e3ticiKxsfHL72NM42NjSVoIlFlZWUrutyQ6MzNzRtzcnLy8CqHTCErUpra1iES8hIYGHiI2l0G02iSLuvu7n6Ynp5+DVHrzs7OnmM6DHz5ElfazYqKih8Icihsyr28vB7g207F7ldimqysrHCktopmGirSnqioqFtbW1tunZ2d/miyj6nLV+rq6toKKHSUlpYmI7IvTlzOudvb24Wn3ocZGRnWMD6siEmFZw+QqHNxcfkddTkAC8nQobz+/n6nzc3NMKxrnZLtL6l/H+UbX0tL6wI+PsIkw8ND5KLe3l4mLj21tvhLECIzzxi51M3NbZJgieQaI4saZYRT/+veA14JZndO6kGPo4pzlfz8fJYCu0tXV1f15+fn3YnjpJ19fX3vREdH319fX99YW1szAeC1FPGFNK/Z2to+jYmJuYOramBycvJTlIRH1nBv/gLqvN3Y2Lj25hsGRrAEg4QCT/a4cIcA1p+h+wtiXVxcfA9kfeyKAthH8/LyhHh9RaYg+6/b2tq8wcOzwHB9Zmbm4Lv8lxJcmkDmKKY/ekpKSh6BGEIVN4KL25GVzxX2qBPeh7xGx0v/148wGEcIESOtfApXe8DaDUDl9gf58yb8i5SFoVMFOJSLJhuysrJ6jCtq/kMdeESxVLpJhy/gsK2zfPyvAAMAVDFmO5bXbNwAAAAASUVORK5CYII=";
		var iconsImg	= "iVBORw0KGgoAAAANSUhEUgAAAlgAAACWCAYAAAACG/YxAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAUgNJREFUeNrsXQd8U9X3v++9zCZN2qbppC3QlrKHIIoMAWWIioooqCAIyhJBUNyCoCKoqCgylOUAJyD89QeCMgQcCIiAIMiGQmnpXpnv/c9JE0hLR1qatknP1881ry8v97335dxzv/fcxUmSxAgEAoFAIBAI1QeeKCAQCAQCgUAggUUgEAgEAoFAAotAIBAIBAKBBBaBQCAQCAQCgQQWgUAgEAgEAgksAoFAIBAIBBJYBAKBQCAQCAQSWAQCgUAgEAgksAgEAoFAIBB8HzKigECov3jhhRfK/M5qtTKTycTsdjuTy+VMpVIxQRCKXTNz5kwikUAgEEhgEQgET4DCKjs7m+Xm5g4FodVerVZ/FajT/abX6ZhMRm6DQCAQSGARCIQywXFcqecxegX4QKVWj9doNEySpImiKPa22WybMJrlLygvglcToAgggUACi0Ag+ClAOLH8/HxmtliYwPMsICDA0R2oUCgeRDGF3YIouOx2+4MymWxTfeIGu0ctwEuhycQKCwqYyWxmMuADRadOp0OOyIAIBELtCKzp06cTy17C0SNHE+BD3SSpyQFig1AVYATLDKIhv6CgbW5u7hyVUrmB5/m3goKC8OszkELwwCkkzlRUvqdNm+Zz71+WsAI+WE5OjqKgoKCVKEkd4XQXSB0tjMXabLYnCgoLP9I4xSgm6jolEGoWY8eNYzyUYfRP2BisbBn0dgS51j3Cf0f/i4WPgZD6QjJCauv8KhlSCqRtkDYkNkncROZUjLeOYFQ/cDynhuPbgZ9tpVwTAR/9nX/mwTUriTlCSYGB4gBE1XNBen1PONUTnNQSOJ8Bx6MhrYYUDQnL31v1hZfCwkKM6rUH8blWqVRGI0euyB6IK5aXl7cIBFhCan6+HkTWtzqdbpNer0ce643teNp4hoZgI/hoBSnC7TSK9QPQOEz2JA9fE+4E72HgwIFGaAD1gkOtmx87CQJrk1ardUSWsZyW1XiqSdSawDr23zEUUm/I5LK+LseFXRGu8R1AYDQms8nc3mQyTYbrsSC+DumjhMQEe302MODiduDr21BjqAqN6FLapU1wbhTwstz9uojIiFZYEeCxwAsX4IMEFuEqgYWtPkgb4M/bIe2AlO38ehekBv7+/iWBXaYYwQK/tEKn10cHgtMueR36KXDmU/ILChiTpFFwqjX85kDJWZb1uAGIkc+JkAYBV0nIFy9cEZ/Ir9Vixev2wJ/fQpoHDcC8+sbTxIkTWU5uLgr2W0G4DwRb6gGno9zEg80ZbDgFNrhWqVIt1wUGZqKQAOFfr8bw3Xf//beD3Twnl8m6qNRqBp+OconlFbvxrVZrRmZm5leFJtM04CgNhVZtjxetFYEFYmA6vPiLQUFBgkqtKvUadFSYMPQXqAt0CK6c7Jz5YIjD4ff3gZg4Uy/F1bFjo9Rq9XwQV4JGo8kAo1Ibw4zqzIzMZfBdREJCwizXtTExMfrU1NSif2iZTE1un1AyIuAWGVjuTJcjOAiwNb8XmCUhSRJWXq3guySsxEqLSrm6BQMDAx3OHfxTF7juQF1oNddy4w/7kqeAv3lGo9XoNAEaBo3oMq8H7toXFBS0z8vNw0b0NPDrC+oTX5lZWdFmk2ku2Fm/UINBjcEG17hHp9iXgW3FmUymOKj7bgauJmVlZb0PYmwuiH9rfeBo2LBhIfD+nwao1bdjlBg5KtmQwTILthSSm5s7Fmc+Z2dnj7aL4kqc9YxluF4IrOPHjqO3XhEUHHQPElUZoJMzhBpQbHVMv5S+C/LqH58Qv6s+FUZ45+mB2sCpIYYQBuL0fL9+/T4DQ1OuWrXqYeAnRJAJb8A1GI4fB9zY3SuQ+u74CVeLq/LsApzYMvh4xN+5KO390XmDQIh2NfIqdKJFLWm987P+iqtjx0J4gV8DPqobNoo96S7Fyg8T1AfG7Kzs+ZAHdlM/Ag1Fv49mPTJiRHNQBt8YDIbmKNRLi7YUCzTANSA0YkA8vAViokV+Xt44bAv5M0cjRozAYUO/AkcJqBnKKo+uoQ6YNBqNFjhaYTGbo/Pz899yRuhr5flrdMAAvOQXxjDjPTiAFgmpSsLCGB4RHq5Sq346cfxEUn1wXPCeAqRlIEynosiMjo4+3LNnz6XvvvPuQ5A63n333R8HBwefh4QidBQ4uR/gem2rVq2O63S6VBd3BELJsSzuZUuEVqDVZnP9/YhrADyOOcLvSiuPvj42prR3clZqAgqESvgmrXt+zha1Y6A8ztDE49J+50eNvwjw7/vCwsK6gZ9ycFgZv47XY8PRaDQOlAmyHZCf3p/L4WOjRoWCfX0JdWFzrA896cpCnjCiDGIDRcRwibEX3YSIcP+gQcEDBw40DB48OPCRRx7xeeMaM2aMAuzie51en4Dv7GzA5EF6C1KL1157jXMiANJdkH5DjnCGb0hICIqtN+12e3+Mxpdld34TwTp54uT0UGPoXRjeqwahxqAgB6ampq6HfNs1atwo218LIryfFgrit2AwfTRaDUtMTNwVERGxYeHChRNArAbZbfYGc9+bGzn+ifEfbdu2bSgYTTzw0yf9Uvrm/fv3DwYjnb1ixYrH0tLSItDp+wtwkD98fM+KJka4A1t0oxObJH7mvO4P+Oh4Dbd6FPJa4o/iyj2Cg04IFxbNyclpBWKg2NoD0HouBKF+CFuQpXUZYr6+Olu4LCdbGSeM4gDKlh4FGYpR4NCRgNMEON8RzkdDw3BBYGBgHkYhsJHoT+IKGnNqsJHvwR/FXGukACtHhVzRBvzV55Dv3Y3jG/vdeNtxjz+uBPU+R61StcJxQpWdGIH2g78D+5oMeS23WiwC2N07YGvdIS+VXRSTc/Py/gDBtVoTELB22bJlBb7IEy8Ik0F4dgwCv+MsL4cg3TVjxoxjJcov+vx1zjQF0pvop7C+KzSZ5oPI2my1WvNqY0mVGhFYJ0+eTAgODn4BC48H4skcGRl5JDMzMzIvL89YnlOD1k4jKIgvOUn1O5w6eQpbhesMoYbrQZhKHTp0+BHe9/Ca1WueB5EldxRMsBm5Qt5o3rx544YMGbLwxIkTdwDf18Hvrv/n4D9bX53xar+33n7rwurVq+87cMB/VnMAB/O2Tq8zlnROUKjUWVlZHxz779hKnAzRpm0bGdhSle4BhbsQbMyQnp7uty1pF38O8c1x74HdTCxZSTqFxjy45gl/myVXiv04xCYOwkYePIks4BphUMFZcLAt/ragoGC42WyeDhVhLDp1zBOuGQ52uQSu+QqEanJ1NDTrCoCnt0NDQ9tX14BihVKB0aw7LqVdegorS1/mZvgjj3CFBQU3wGEPbWCgSiYIc4GvTsDVgzhQvaqTIrArDGxJrWTsQRYQsBPy7Ie27BT5MWCDMSCyBpoKC7cPGz786U+WL/ep4TSTJk1SK+TyKW7bc+GKAr1feeWV5PLKLyua6YzRzxeRXyh70cDTSCjPc2vDd9WIwAJhNUcfpJd50mrr0qXL6h49eqzKzc1tNHfu3NeBmDJlp7Nf+snTp06/F9cwLpn5EeCdEqAQ/hRqDI0DNW7r1avXV5s3b7anXEiZFBYeVqwFjI4tPDw87IsvvnimZ8+e77Zu3TobxFSPiMiImLTUtF9GPDLinqXLls72J4EFvDTCCq00gJjXq1VqHRxmTpkyBR10iyreBltGP/jDWm5ldeW57AgjK5Dal5NFo4ry90WeSvok58KiRnDMU13dXBXBKaBwhtNHcJwMAmoRCHMFtqLRqWOeJpOpeX5+/hzIryNcM9hfIljQCEyABuCYsiYrXUskC4TCVMh/ccNGDTN8kZsHH3zwHvBRL4HQbgFlSwn11Z9weh6cexWOZdcaUcFIFtgSCtt30Neh63MFH1xRrry8vK45OTn/9+ijjw5ZvHixzyx1BO9wD44rxtmCzpLyOviY5IrKrxMzIA2FFCsHjnF2Jsfzc2ujzHldYJ05fSYBnE1/T9Xj7t27j/7yyy+rwAgx3DyzIlLAiGTg3LClM9lfxMOZM2c6QgHZAEIqGFq6eSCuvv7qy6+i7KK9rzHMyAYPHrwoMTExddGiRYObNGlyEATpwbVr13b++++/e27btu2ZZs2azevcuXPu77//fntkVGRwWlrahpEjRw6NjY39w184AqfCO7dzKTUqkZSUpEi5mIKV/leM4KnAQMeEa9I9yK5ME8fKDafRb64H7++wHWg1t0UhhBWgJ04ZrwN/lQSOfDhUDGvAbyncf4uRMGxNo+ACm23kGtvlDwjQBMwB8eCV0AD4dk1hYSG2DCb6Eidjxo6VFxYUvA0icYLOOesNV/83m837RUnqarNa26nh3LXaAAopi9UaahdFpWi3W0oKNrQ77NaHz7DcvLxPx44de+uCBQv+8QUOMcqHz89f6QJc4kn5dcLCipYkek4hl6NA64R0gRi113QUy+sCKyQk5GFtoNbj688nn5+Wm5fbFcjtEB0dLfeEEDCiu/1FYJ09e7Y/bqwbFhamwgHqvXv3/mLxx4s7K1XKDjgzB/HTTz99uXLlyq1QgO88ePDgLhCks4KCghYCVz3Dw8OFY/8dm3jp0qWvbrvttpVw7SA4p7qUdukbyPupmJiYd/yBJ1c4vKKKE1rAOGioeRVvkwet5yP+Gr0qxUFtcqa+bgILW42jr/U+viKwnN2j9orsq2RFhxEXEFk4DkuN47BK+60zT62/CCxoCIaAn+rnrUoL8w3SBw2D+6Bv94mxWBMmTOAlUXwXfPfjKG5cSwRgFBMqeBP8q9/rWHW8Gma1ObsDMYwVBXnzZY0ZRHEPiDCZTAsnTpzYY+7cuTYfaEDHOgRWUQT4GPiWwrI4KA2uNemcohPFFQ4nSfE7gaXRam7zxJkEBwefjoiIOA3GkPvvv/+GZ2dn6zwlA65rdO7sudgGMQ18em2s5HPJY8FRfwBOSwBherpTp05fLVyw8L6g4KBG2Bftwj8H/9mCs5LCI8IxBNw2Py//DfhEDh3fhxpDcZDtoFWrVm0YMmTIsg0bNjwE12ozMjLmwD2wq+fJ6AbRPj14tKIKEESq3VlhHoMUVZV7iJKIEdgZsXGxfruMdEkOXVFB13ga/Nu1GGl9eH9nROpkFfPCRTMF5Ku0fJ2LImrL+t7XoAvU9Q8ICJCBz043Go2nq90fJic3lTSSXpmj7Ax//uIjiv0B8D1jSu5TKRXNwk2EwwZYtqpDYGOeYE+ZkLrDcVBZAsvVAIBrukAawtzWu6vDESwBfQ4OA4FU6GkDyeG3ixYKLnQ1mJyTUBS1sQiwrAaIiq/ImbRo0WJLdHT09saNG/8OIiGtd+/e8Z9++ulLUMBaenIPFB9h4WE3sVL2SvMZcZWc/AYUyudwOioIxb9jYmJ+Wrpk6ShwXEElF+obNHjQajifsXXr1j5RUVHHmjRpcnzfvn1tTp48eb3rGmw95efn912yZMm+kSNHLt28efMDYIxGKNzjMzMyG8D9HgTOfXYNlaCgoHPp6elRZYirrKEPD83BMUFdunY5CWKdq5qv5CT4d8j5+++//VVfXeWgSq6b5o9LClTkoAEosG6DtII592KsADiL+T5Im6DMjcSKr7TxNXgel72AT8EGNUCAjy/iagg13Iy+HfzIr/fff//i6s5/8eLFr6ampraOiIzo7gsCa8qUKVqFXP401EeCe4PYKXJwwGgbjCW4IjPXCoyUAsIhDQO/Li9PQKA9Yhe1xWod+PwLL6x8Y+ZMSx0XWMnIEZYZKCqxlWkgORf+beRqyDgbi2l+OQZL4AVtRS+2c+fOHoUFhT1sdtun4eHhw+DU7oT4hF7wu5ae3ic0NLQRTo32NVw4fwE98aJQQ+hwfZCeNWvWbJvJZDqwbt26CZGRkXL37SVcAIH0edeuXf/YuHFjRxAPO5s2bbpgx44dM8GYrne/DgcuQ8FqC0It6OFhD3+6a9eugXBNnEKuuDstLW0b3LtvZFSkTw4gHThw4Lzt27ePunDhQrz7eRDoFzpe33EjiCuHAxk2bNgb8BFTxdugU/zJnwRWyYHoJWf2uhyW+2d5ERfMz5fXwiqnosOtg3CG8nwPssHdEzbl5eU1h0pvUVmrvzsVXawkivMhjfb1KBY8f5IzKrcD7GBddecf0yBmCOTfGnxY87rOxcsvv4zrpt0KqW1p++DhsmqQwt0bLdVhu3CvVq4oVUV5otAQJakDqJbG8Oe/dZlPeJ89rvcCsRTx7LPP9pw9e/bmihpIGHHHRgxWEa6FfyHh7K5aCSZ4XWCBQBAq+ofHqA0zOMZrqZKTiyYKnDp1Kk6u8HzaLxRClS86qYiICH2fvn3+gXdfDO9gO3HixF8glhbB+TILzLZt22Zt2LAhF8RRAgiMR8aNHXcbtCZjMSxdSjQHWwMNP//s87tfn/n6TODVIcIKCwtTN/+8OTg3L9cnBZbRaPxmwIAB5+EwscRXeO5XNwHwAyN4FMHB1qIruf7GcLs/7wZQwTvhti24VMxU9PVlXIPCwrEJNlR2jQICAoSyIgl4Htf0ARHW3h/GYYGQ1GEUBRqEZ72Rv120X0Ce8D4+YEfBIGBuk4GIKW25Cm+IabfojEdwXhsOZTqqrgsseLc18PEBVu343Hn5+dMnP/XUtnfmzLGXxatzE3YUWf1xkLxzE3tXGa2dSJy3bwCiwQQvHuCBgUodO3ZcA2AXUy4mhYWH9cT1UDwFCIl8X3RSr0x/BbeEcG3CbP3fD//rHBYWVr4gDTU0wcoPDQ8MKUCr1UaX14LB8HBUdFQIOKolSUlJ37vOt23bNs9XlyCA5zaBnfwHh1klvioMjwi/5PoDrsEKMraq94G89tQXgYUrjoNzMsK5ENfgXKg8Y3GAKJThNOdg2foksBA4s/I3SBtL+Q5nNuEEALuznOGECCzP2vLuB9f5hU1hgxAFeGZGZqA38i/IL1BXVkTUYsQlCKNXisqPr8JBj3ucfgyjUdFlXHeUFUVVcWNxVRWf0dVoCqrrfD7zzDNpb731FpYvHJfMTGZzl9ycnMVjx44dt2DBgkL38oTvBH6K4XqHBQUFKKw+xWCDc9yoxdlQ8k+BBcLnEjjuCis4EBWHW7duvR4FVqAu8Flw5nxlDDUkJOT42bNnfc5JgVBAY7lsMNHR0TKzxVzub9z79z0dfAyFi4N72Z0RHp9HWmraQHDwK+C9iqlwLGzw3SxjmPF5R6tNId8nE6o2yN15nxmQl98Mci/Znffuu+86PjGsDs4Jne+nYF9aV8sQ99gD5/YpCKzbUKiX3DjV17fK8SSyYLfb95XWTQq2tgbOu7eocYVpXFRyfzkRrx+Yh7My6zrATjLQbsBfXXfx4sX2Xqg7mji7wS7VdS5ABOJYPX0VBrCjsBrJilYpX+QUUFeZIKT3IS1zCrB7q1zhQ31hxymNvtH4wS76e8DHRwQHBWGBG56Vnd1l2LBhoz/55BNHd+GpU6cc23tZLBZcuv21QJ1uol6vF9wag6+zopnQ/imwQH3+B467QoGl1Wi3gwBwbHljMBg6VSakCkZT2L1799/9YawMx7wzoNjfunfARp4PCg5SlPZe2VnZky5duvRSaGiovU+fPnsuXLjAVdEZmWNiYi5u377dbyNYroUwMXolStJ4qCD66tw2VcVj+L4vOLGJcM1cFFm1MRuntiJYuDI7iEsF8uQ+Xs21RyNWqCUGtGNF+QQr6t4oSRSOBXnUX7hTq9Qnc3Nze4BdjIbjaheNZpMZZ6HjWNKjPiCweE8Fu3tjEGyIh0aNCoUPHAtoT6XkscIprnDLG1zzEcekNatqFAvyz/QF+3r66acz3nnnnbvgcCs07NTh4eG4plhCZmbmzyNGjDgDfGHkLw0KcSu1StUehJUC93V0BSAsVmuG3WZ7R8AdGWppI3avCywg5af09PRbKrou+XyyyXUcFxd3LDs72wDCzOjJPYxG42Eg9oJfOHye81p/vV8JrFBDmf2oILyUEpMcK7n369cPByC3ruJt0CZ/8meBhXBuRtwWbGSOY2KEW5cMHuM5KI9vWq3WbXDtPgy/+4tgL+09nCuzOzZqxokzUPlNRQ7cr0VxBd8PBPH5A7aWMblFk11jt9z733Grku6slgbbegMNYhpsTbuUNgI31sXkpX8fqXnz5j/VdS7g3z6dXT1cwRPBg1NJ5U6RVtpYs32QXnCKKwQuh4Hrgn3JiraEqSwwynrSV2xs8uTJu959910sN6vBFqJxdjyWRSifseCzYu2i6BBPGFl3HyaDZbggPz8Eyu9aOHdHcHBwIZbRmvZbXhdYnTt3XnX69OmnQSwZyrsuLS1tTGZGZhocbtBqtL+AAwuB1qNHAisiPGLt9OnTxfrSqgYVnwYOrVh/aEpKSjPgTF1fIlhymZy3i2VHuhMSEhTHjx/HLlgc8P4rI5SuIE0m7BrELsEvNRqNIqCUFabxHEZxQFytgGs74ObP/rKXnutdUTAVFBY6RFUeJLPFoofWby+1Wj0W3rVnSV7QoQMfw8GBq6EBuQQq2M3QcrajEw8NDcUK93JZxAih2WxOgd8XljvD0MfQvXv3jceOHUsFHsK8dQ/wc8datmz5tw/YEUaFsGv4Bg8ux4lFOBZ2NbZ9IbkWM54D6RtWtPTCq5ByWVE0NBmXHnDZHwgxHIv1LKTnIDWs5KP+BemcL9nZpEmTds2dOxcbya9BGgnlR4GNGXUFy5ygGBNFsSeU6Y2ZWVm47EpeTTcOa6KL8Di0QL7bu3fvyHIjEgaDkuf418CBv7Zj5w5Hi7C0WXGlFMDjPXr2+PyX7b/4hdMCDip0wDfeeOOn4HSKvfD//d//PQlCtkd9iWA5In2snJXcnTtYZWdlJ8HHzVW8DQ5YXqcP0uf5MlflLaWAs27QsStVqiQsb2UtkImtRhAhzUEovAe/Ge1YjbrE4GNfXLIB3w1FFQ6Qzc7J6QnveDucw814O+GMP+xyKBGdcgC7IVBIwecg+O2g/IKC7Lz8/F2QfoPjNY0aNpwGv0FyX8TV3eGavtBgbA7nDrm6MXy9qxX+vS927dr1fwcPHhzurXskJSWtxHGqdd2unnzyyUvvv/8+znx7rLzrMLICYikYbOEGsIUZIBKOu9nBH4Um0y6rxfI2x/M6m9W6Jzs7OwIE+lCwwS1gM+eg7LWH3zZVKJXy4KCgw1C/NqyEb8cgxCcTJkyQfM3WJk6ciKJ0HHCMk05wpwnc/qYtK+qGx8AMdr9vdopXnJDiGA+HkVXgpwuU7a1ZWVm9oWxn1KTIktVAIRShcMw5ceLErWAsceU5OkOogeF/lXCO9lYtWy2De5zwH+VQcbTpwP4DG1atWlUsbB4XG3cn/K5HfYlgORfuKxPBIcEWdtxREe6CVKVp3riSu6nQhFsLPeWvESxw3oPA0Y/SgYAqr8JHgYGOCYTCKOwWA1GyzrVzgC8DBSa8U0h+fv7qALX6ZhSSWkgqpbLCCSQYjcKETtxqtepNJlMv4KUX5DkVGjvrYmJiHobvd8ClP+P4EKgYt1+6dGluWlraOnD++/xhViZuLn/mzJk+8M6R1Z230Wj8t2PHjkvWr1/vK2J9CyuacdqpPD8M//ZcQUFBUlZ29mKwl7tAcOegHaHIB4E1Wi6TjcNJXoBb4Pwt+BvwYffA8Tkoe8Ph7/Gu2XM4i7MSQh3rjPW+bG8gDlNY0Ur0mNgHH3xQ2mW9S4os4Kt9Tk7Oz5kgslCQldWY9DmB5RRZh8eOHfvuunXrpkMLWF9d+bZt2/b/WrdpvWTNd2v8SF9VPMjdYrVctZeUXbTb/XW17dIQGhr6b2pqaoPSvoNK8ly/fv3y/vzzT3Zn/zs3QqXWuCr3gAJoj46O/mft2rU+z1dp0aWXXnoJNx5ehKKi5MrTpQGvwWvBUS2DVngHqCROuufvi8DuURBS68PDwzuiYKzKlkBY7lxiC7slcPwWVJb9we62GwyG3mq1egmkUXCPEPicDg3N6VCRZsM12x5//PG3Pvzwwx0+bFf777vvvqVbt259Dleor7aKSSYrvKHjDfMhf5+ZGv7EE0+Y5s2bhwXh+/LqVtcmzLjFDdSHM0BkPYmTKSxW640grqZB5a9ydUmjTeJWMSCsCuRFa2wV4LqRVfD1OHt8wvjx4/1mKI3TR5d2Gsc73uYUWY4Z0cgZLqMBvmsrlD8UrSn4b+AXAgsRFha2uEePHjGbN28eDQ7omptuiYmJ2zp37jwDCmCKXykHrmrRpoqEmavLzF9wxx13zDl48GBmcnJyyZXcU9q0abMe7MKxqV6nTp2w3z6uqgEeSH/4g8AqDYJMtlipUOgrM/gTr8XxkWaLZRGk3r7OAYjG4eB4O2LUSlZNXXbYfYrdh1BxtoK8pwBfGLEahbMQMeEiwhjxAmffPysrq/9TgDlz5vjsJuzNmzefB+/SdO/evfdWR37YMwHldmXDRg0/9TUuQMD8CIIZWzKvl3cdiiWcoZudlTUORP6vYA9bwTZmg7CKQHHlEg6uNZ7AlhyrK4CIF0vuc+ihuHoAxPwRf/Nh5fit39xElhpFrbO7sDkILIfIgmOvL99QYwILKrx8aEG/BUZk2bRp0yP5+fkRVS18UIH+cOONN74Lef7ljwZTUWVX2vcV/c7vBrnL5RvbtWt3GlLJldxRcO9zszscIOu/mwlWMYr15ptvdtI4B29XJlTuGo8lKyzsBc6/I7YWfTV65RRYXRyRgWrezBodujMKcTPk/7p7+XNFvIxGo0Owgi+cM+PVVzdPffnlfT5qVylgVzPgPaXdu3f3F0VRcQ28FULD+SsQbTNdy/b4YFQFZy5jSPhFxsoeKIp7UYp2uxwE+MuCINwKttjNbYHMywILktJisbwNKRmua1lO5KY07IX06NixY//yR59WQb22wymy1pcQWUnA+XbgtQXz8qxeWQ0XxItQEGcPHDjw4rZt2+47c+bMDVAYPX4GML6zN9100/cNGzb82B/FlccCi5HAcs4aPexMhEqKLChLEVXNQ35lO5BYyG+XL/MBTtco89IaOc61jZLAoWfY7fY0qByvmhXt6gqC73u6Nwx80K72g129YjAYUsC3D/J0Brg7sGv/1ltvXRkeHr4A8jvlq1yAmEHfNHXBggU48Bpn+5W5CCtGNMFOUDS1xLFUJbuonQ0aHsRXW6gr2+I1Hq5sjzMace2sj+F58pmfwoNyuw0SrqWF3RBq5M+xNV/RMioKvxJYzoKYDQVxft++fQ9lZWXdsmfPno4XL15MzM3NbVCGM8+Dlt7RxMTEg02bNsWZc9+jUPPnSrBCo+FKP1efBBbh2kRWREQE7s91B6QukCq7iBFuP4Eh+G99nQuouLw2EAMrS0g4HEIBjj3D6dSvgnO6eSM/sKt/wLe/Bg3go7/99lvvf//9t6vFYqmQX3j/tFatWm1t167dJvjza1+NXJUitL5ZuHAhDnxH8Xw7JNwHFpdgULn75YqWG3BFPMsBzlZNhYT14k5n5ObAmDFj/Gv4TNWBdjXAKbJcogpFl9ftTFZLBRHHx2yCwvjrLbfc0gGOm2RmZjaDFJidna2H1k8AVAAXwDnZY2NjcYYgbky535dbNZ5i6NChf7KiNVDKw+GS3TLDhw9f4SxkZSHbl7tyCNWLlJQUHF/2A5Szer0ZNlReHWroVk1LOzl69Gi/4tPZ+P0AfPvOTp069QCR1frcuXMNTSaTNicnJ9LJuT0wMDA1ICAgG8TY8caNG2O05SecDOVv9gUiB7f5+dqZCDUdjLiCDc4G5XhION5xW008n6yWC2O+80W3QYHUBgcH43R6bPHgnhQ4MM/u79GqUjjBlXqnVuF3uNz4dipyhEoKLcenJ+sMkUAnVMIf4difvWBXDZs2bYqzeDGS59oTFMX9RWcE4T+49jwxRqgBbHKmmhOAOIjOywWN/lkJhHoCX9/8uSb9FXFVf7gi1E/wRAGBQCAQCAQCCSwCgUAgEAgEElgEAoFAIBAIJLAIBAKBQCAQCCSwCAQCgUAgEEhgEQgEAoFAIJDAIhAIBAKBQCCQwCIQCAQCgUAggUUgEAgEAoFAAotAIBAIBAKBQAKLQCAQCAQCgQQWgUAgEAgEAgksAoFAIBAIBBJYBAKBQCAQCAQSWAQCgUAgEAgksAgEAoFAIBBIYBEIBAKBQCAQSGARCAQCgUAgkMAiEAgEAoFAIIFFIBAIBAKBQCCBRSAQCAQCgUACi0AgEAgEAoEEFoFAIBAIBAKBBBaBQCAQCAQCCSwCgUAgEAgEElgEAoFAIBAIJLAIBAKBQCAQCCSwCAQCgUAgEEhgEQgEAoFAIJDAIhAIBAKBQCCQwCIQCAQCgUCoXcg4nlfAp6XKOXCQpLK/fmXaNL8g6pXp0xXO97GQ2RBXxFXNw+mrmCSKxFU94wrex5vZK5yfXqsH/QjEVSW44hjHqeHA5B2yJOcFfkG4yvlJXBFXxBVxRVwRV8QVcVUuV7xnb1MOpIpY8IAprxPFVVcmxBVxRVwRV8QVcUVcEVcVZiKD/wmsaCzWtT8yhy8ueX6+YrarCVJ1sC04j4kr4oq4Iq6IK+KKuCKuyuVK5iSKq55nkip33nfAsSsTAogr4oq4Iq6IK+KKuCKuyuWqegWW/6L6DYu4IhBXxBVxRVwRV37LlUtgYRKJE1ZWaJJ3Myziirgirogr4oq4Iq4I5XJVfAzW5ZH5Ho7kr7Kwq8Phv8tEFeOAZyX7nokr4oq4Iq6IK+KKuCKuyuDKXWCJV96Bq/53uqzyfKVvlSupRoViyp24Iq6IK+KKuCKuiCviqgyuUGDJnaTZi6uyahaavj1oTXDyxIgr4oq4Iq6IK+KKuCKuKuIKBRauzIqftmvO0n9XZ3XxxIgr4oq4Iq6IK+KKuCKuKuJK5jyovrWw/A+utT9kbsqUuCKu6gVXsr7vPcDs1nYSx62yb3z6D+KK7Iq4Iq6IK8+4chdXXPmLe9Vrskr2PRNXxJXfcyUf9O3bTLKPZryccZI4jhvw6V221Q9vJq7Irogr4oq4qpgrGRAkAEFF0y8lqR5Ouyxt9sNVswGKDKvImIgr4qpecMUZEu5nMjW0w5SM2QoZZ869H05vIa7Irogr4oq4qpgrGRDkHsWqp2Kz3HMu1S5zKvU6w5XQ9cXGUAGq7FteOkRckV1dC2T93mnFBPXrTKb4ybZm5PuOk0rtOcbLgh3HchBaknjOO89Yd7niItoq+IQ+zTmlrj0IzRsZJ7SHCqYBPMcztg2TlpNdURkkroirsrhyX2i0VvpThU5PNeBCm97FZAG3wDOGggNrVSQIpQuMiReZ3bpTMmX+bP9x0pZaYtOdH1abXBXj7ZZZ7QVjk6+ALzXrPed++8andl51TYdxYVxEm35OPvNsP4z5tj5yVUdRp7jiYjtPYry8Gxx2E7o8/bl9x9uZYvrRSZyx2WeM4yOZaNti//XdD1jtrOBcK1zJer/Zlin1K5lcFcmpghhThzBOpWeS3cJY7oX3ZLfPa8xshTqJcevsPz69heyqDF910zNxTB/TnBMU4Zfb+zbzWZZ5/JD9j7kXiCvyV5XBQEkKbcpYd7i51nXOzNjp2RxX58og9qHeAAepkPJYyWmXXlw8TOg+vRUXEv8yJ9fcwgLAcSn1cFIOLeWAogvQidmtTDLnAHvZTCrMvgCf79i3TvtEykuxV2/fb4n3LJ43KlH8hwxz/l3jXF3FXZ/3eguh8cuZoakSKj/G0o9Yxcwzk0BAfeF+XdTgRd3SlIlrHJUFJ6YULr+1RX3jqvJKo37alWzsrgc4bdhsKHO/25b1ekDKPGWv71zJh//0B1NoEoAXyFYo/qUlj0mWfMYK0jGyx6T0o11t6ycfIrty1jAt7g/mG/cZzeTqezi5OsERAeXlVy5A/24tZJK18G9mLVgnHv7mY/H4xvz6WgaFHq/cDHVhf7CzrvCMEXA/jfMrmzPYcAbK5nox+Y8vxMNrsuqjXb3EWG8dYxOBmBtRJaidd8KpjAVFKRPSmr8Ym/01Y5fqQhlEgdXJSVbu1WR5yZnftfRZTmOczOkbCAxbhp4ACqSUc55JuRf2Smd/HWHfNe/cNZPioe1DCixhWDXG1VXc3bnwYS6o4VucIVHQqfg0k40FWGyiBipEJmWefNW27tG5rmvbP/FVnwOyjivwWCNY0jPfTkqqT1x5p2ARV/WBK1n/hc25mBt+YUqdc8OLcoBCK+/CFOvSW5bVd7viQpsqhJueHs+pgsYzbYSOCzAAmapyuZMKM+AJU9IlU+Ys2/ejl9WnMihcPzqSC2szk6l1vThNhMrBl1zjXKIS3keER7GbiwINeReZlH8pmVlyP7L/Of8jKf0/a33gagDHBXdjbH4oY72i4e8QdmWtCBdwIBiq84uQQI3mQ7Nn8vOStKq2y6Br/JUreeZZy1wcrPylXLnoDirhxgkLWXB8P6aLcq6z76nHUwKzjRinNV7HKdSbmMY41L5l2t5KFv8qlQG3xGqKq1IpuHvJMyy48dMsuCEzarhTT3c0LZLLeMW0XxTjc/h4I5MpXpYNWB5n/3HKs1J+ml0U7bzEcS4zcd+o0++5Kl5GvB3F9j+u5JMOv299t9mEesuVLiLKEXURZB4UTAUmPav2MSm+ZVd807uD+Zb3L+N0MTdxgZFwQqj4fkoN4yAxXaSBZZ97Szbg027i3qUTxFNb8/29DMq6vZDEwlosBq6SOG1E0TjHku+B9odz0RTAkTaMcabsaCknebrQ7cVm4u6Fz4hnfzf5s109wHGGvhz3v3COaxSJ5lLOw+mcCSSqJlmSFn3IcVGPi+KHtVkGXWOwOLdPz0Rd5b4oMqjOkxYxY4vbmDq46u+rAmEY0crIyxXfsJsm97X/+s4xL7fk3flhNcVVMWiMgqzvnHeYIWEwp4tmCSHSX/fH53z97FennxA4+7nX7kt6953dAaNS+diGkkL1sHDb3Ab23QsfbaLNPnlewc5nFHJRrEhocX7PVV2Hj3AF4moiq+1+3NrkiuNljiELHOfZc3K8tlb5qmW74tsMCROa3f0jMyRFMWVg5a0QucYGtFp/p9BxbGMQrHeLxzbm+GsZFNo8FMJFd/iIacNBXIVXHCV1PB3U2TicRg4yQ64aLHR6MkU8O/gNx1dQR3ARbQNB1HLMkmcVk//MZzaz5MtcNeU4+T08vxIEU6MGVwIF+bmMLd8jSV+OsduP4rmeHKd6mudvjuW4CWBFHQzYQITrlZI07QNBOP6E3f5jbZVB94VGOW86CNk9S6aAWr82cXU5M6DR2CxQEG0rpdQDvcRjm6q/IErumyxdtcAaV1POlIvrohE6jvuYMzbpCUKLdYiUtrQISPt55vcpzzFjkt5mt0Q9/81/4a/cFfvhksPBw89wYc3BOfWU3fj46r2Hdj/62fM5U5/YonviYjaL8doz1wJXQrdp7bjQZp+DURtKPIxJyk+dYt8w4Zsiu1uxHsy8XZVfrSBtsn39+JX+ZldlVpRdJjZjoigv0YgziTs/OFrjD1ObXJUc0ltRK1cm15V8Hr798EZcUEw7JtdGiIfXfiKd/jXfH7niItup5C3u/lwMax3l6Gm4FmigOCvULeTtH5lvPr9nOCtIt/uVXWHmEa0VXMuB06WA0GZcYASTPBFX7lCAlg+MZJJcOUbo9sJXTLLznLHpDMlacBMIfSUTbSlC83v2Mkv+D+KR7zdI53YV+iJX02SysSGMtYsG4YLF0MbY0f+J4rCnbLaT7uGlzZJk3my3b4TDjb/K5eOMHDcVBx7Z4dkVjM3uKUk7N4tifm34K5fAcoksr/SnCjeOb8hFNJvANCEVXisXWGFCkHgwJY+LyTTjYL+yHKCMSeHN4uTXDXnSfGzTa16kTXDjiHmbq2Kv2GpQmNBqwHIW2qwtFxAk3hlvX5WaknzmkwN501hEC3mRPlZBQWsaN23dkSljutvf+01t6Pd3WnBnFtmq7ak0+br7pq148Iepd8x442/jvT94f1ptjXGljm33ssXQwnBVy08SVVzmydft6pDvWGGGPa5pS+tZk65K91AILL85O6Tetd4rvNWaXZX5QEO+msHslkcdjsIVuXEcC0xo3HWZ/bP7X6ytR6tpriRzLs9ZC+BOHowRley4TpjVJceE/h8MYjz/NCcPiMZoDo6jETqMGCy1HPCFlPrvWvHPxSn+xJW886RporFZGyZXVk+GigAG+fWS95411vrdY/N9mitByfE3jL2O00XexGnCleLh7xZzTW7rwNTBAzitsShYUCUHGMg4yariEnreK+Ve2MVFd7gFg66OblmbKUoqyIhieRfv4LXhf7D4XjPs217/y5fs6nqeV4Xz/ONY+mTgi0TGUj+z2QbPtNlSymv23GS1LtylVOpDOG5iKIoySYocw3EPbbZYFteGvyq5VY5X1KiiSY+pVl203JNw++DEgs+HxJ773qIwRNy9PuR9m8iVXWrlaiiISaP4dkOXiH995i2nxbPStwjwaiuHv/HxhnzirV9KYU1jBJXGOq61+ePVf5zRncuTPcWFN2OO2YOXCVYzEFzGBTuPTO3T1DynZ8PIrJ/PBN7OIltH5Qvytd1mbB35ydC4hT94PzpSY1wpwxo1MHPyUm1bCmmoU8V20JqObMxZ2idzdliYPLoq9xBF0bJp09G9u7zDW63YVbkt65jrW5cZgbAWxNbis9UoV9x1QwxMHzVZwrqD9+AWko1JPHcr3/PFFdLJ7SmsQbs3OYVG7ojWY6UnQtu7MKsJK0ifxoU3bcf+XDzWX7jibxjXEBq6wxxDN6oT0BjnIpo+yTe57Qvx6PosX+SKv3X6bVyAYSKn0iexwEgFkyn2MaV2OWdMfIZT6mQoJK/BSh1CFD5aizvnfCQ06pINDSF90VtoGafU4jhCxvJSb2AawydCn1lP2H987hdfsatJCkU/DccF6UAz4A1SJOl9EFcXPbnfcKv13e9UqoHwgNEB0EAMY+wOOL2kNvwVkiV3kuaVdS34G8c2tIYk9GWCZ0GA7X8fvbT0kTv3GLuNjJS6vsRX1Dct6SJl6pa3jcr/67NXveFrnZy4eGLe5OoyZz1fasvH3rCChTfTB6iUuY+3Llwyf9PxVvlywy2cMYrN6Vo4q3es9fwd/6cd3S3KtueZ9qbdk7cH9Noka3Hnhv+OPdvceHL+oKYNV3zzn2qQGNVKzysUK4Z9/Q8OWD7hzfq5Jrni5HJo1pRR1ng5CzMEyc/AZTd37/5HmU9b8onKnkHH+YNdVagTUv95jwtNuJ2pdHdfniYuiVnMnPuDlHNhZzEeam6LjBrnik/q25LThrVlOLDYkzFYUNFxYlA8F99tkBQUvZ7ThMqZ0m1IFo4v0hoZp4b2uCnbm0K1xrlSNr3lZasunPfGK0n6GK38uocmm4+un+ZLXHFBMTKhx0tTmTZsBNNHM8fMQEHBWM75w3zLATcwZWBLFhDkmXgvN3QIedoKQuA+SmYrtDiipcUMWQnPAm1LuTKUKVTvCz2eH2Tf8sZRX7CrSJ5vr4WyJ0CCzE3PFRZ+6Wm5OSSJthyO+87AcY87nJgktTfyvCxNFO017a/cI1j4aa1usgKTutybrzV4fP0Js/554YEVN2cqNa0dnqlCIxSYENq4Dxy8fvWrXnMlwJXgh3mTK0eZuP3NXnxU6/ksrJkyRC2cn9gie+lr68/ebg2MbscCinj86Ksf/pi47Mk90S8fGP7n3ydPNBva/7umz21pw+RNGBfeRDiUcfqJS38dX/3ETbEfffiPZqQtvLmSE5SLhHsXvmpfNebj0t/Ux7jisGO+bNuQRHvRQm9hzVV80h2JVXLw5pwCcdfC4/5gV57AvuTOHfCxQ5h2tjvjhSKBZben2Gc3e/5Ky8w5bdnT9/dFrmRykQUEXr32VZmFFh4FfRwn6kBABTgqvtJsE6POMgevvD9wxSX2CrIZ4m9lvJdGHgCvXFiTgUwd9BorzLL7BFcKLc/fNmu6FBgxjANxheOlHBlhFFM0W1hgxO1MGcAkuaIa+JGjnSm5yNaRkmTlGScV79lwvVIgdpbZjaxR19ls99JBLPeira6XQY0gNFCCXeGNTYyd+tWOC6d5OFQDniaV446ECoJj1qFNkoS75fLQj83mtJr2V+7LNHgl3McbYm/2RKlHacTj8YHWY8b46Oxdp4Pjztn0Wo+m+QIKlIaGfPuh0eKez84XJ1q6NpqkYhtcCt4OjQp3zxvKIppPZ8ZEIUrLjg+JTV3xyvfnh0uG+FimujKO6F8haY3w8Cp20cSzlHz9dXD8yn/5KsYFFz04Z2jI0nJTBny05fjPz/du+MGcA7rRBWGJgZJc+bJw/7JY+7pJ05mphMPyMa4knit/mQ+7SXRUab2m/wJOLqJKryXZmRB93Vz7mlHv+DJXlYa1kLvc5WMtLBHBq+Tj+SBXUtq/57j4rlUQ5LkHmABOCyu60nwebt8myDRlPrePcaVpd8+tpgCDLEjJUuMC7cerO/8jWUJrU2C4Xt51Ygfrxum7fIEr/q737mJBDYbg4HXHYHQXUGDJVI1ANEY6uuG56vjnkHCNrGwW1rQTk+z6otmspQl7mSOCCq3O64U73hlg/+Khb+p6GVTwvCAHgYWVlFmSTJW9TwHHmazwe5SxcrCVIJ5XeJRHNdsVbvaMewt5bUaARWVoKFUgsG6JtvyvpTL1t8biqf1STkrOo52SjE8e0j97JJtr79FNVBpmaHZT+7Q9n1XftgvSZcquzJ4oUrde4YoftORZKChjGYij5iH2Xe1UF7fM3pI+kUU215dcqG9Yj8RPE/W2Sx8e0tzTvInmcI/I8H9Xn1Rfvzedu1Ir6CNZgUxxy8wNp8Kf6x0z78MjIY9kGuIimFw5jB/4YYS48dWJLPVfky9yhQjVSmezC/kGpUZN5WIGS9mPi/tybdq1+feCWVXFBfmY2J6Tp3y/phqfvxa4qrwxclcEAu/F5T3qKFfihmnnWHTbYVxMh7kg0Sse5S6JudLp38eJy+7dLoxcO0iy5LFSx9eg8zbn4VR7GSvIsPs6V7rIxh1MUIm11OVsn9zw6GfVnf8zR1q+fCxP1d7YuOX10HL+s65zxcV10nDGxNFcQIjAVNoSrWdeZAHa5mBPesfA9uoI+tks+KShnNYwEPy6rNxhOKAvuABopEsx/ThD/Fop/bi1LpdBSRBSeLgPFhK7KEZX9j4qno+1wO9VuFwD/L3Fas30uh8rhSsUV64Trv7Uat0d2yoPCKxIrf/8T2q/nwqz+vH51lW2zyc8DadO3TT7j78ZF9ve48JuCItIq34CeTeVzjnVbfVyFdRAzt/+xkwuovlApo9i3SPNG8SsC8c+P1LwFItqISttDFryod9+FpN/3s/FT7kl+/z5/Ud2rvjK3HhUKOMbFW92B4Yym0LVcuamY/onb7Yu/TI5bNB5PjKeUyj7CP1e/VrcuWCY9N/mLJ/hyg1Pxp9e8EVGUt7RLFnTYpFQrXTugZhLG6acPYtlk3ux4f53w8LCDFUqL4C16zb+870v2tW1wL0lzNW66KsVrsQld/0iTNwxh4XGVzy2Myt5AYirHXzfaU2YPmJmuRWowKKEh1e8Zl942wu+zpVNHRTvaDxnndzX/667/q7ul2k7c/dxiY9qz2sNCayul0EQVVynx7owta65pNZdHcGUyXmobkMdt8BuvOqIYAkCdk0X+T9BXvGYLrkK15FszV33YJy06dXjdbkMZnPcQSO8H9Z+NsaMc3W6zhNzcn719PdaQeiH/OBIErskHdlts5lryI8V40p2FXmVfYgK+ixFQSFUaEyGWLhpLEvizor/OO9/NM3cmOk9fxSFSlVOCLDKq1uXFJ+surnSxLYOfKhrg10NowPOBsgyrL8eOHlu1fng91lEs1L604uwJT10mo31K5BbhMapuYqwP1m/OxS5QmSpfKkDmRjRLOa9X4489E3/zOmHbFGt8BUycxrmfHImPjD1v83ZvsKVO956ftzv0195JaNhi4Zh7udTU1OzPl322THX/e4dOPBAdUgOX7Ora2qIcXYcT+TYY69oiEV1OCbf48o+t8sKYcoeAwuKfoJd6RopDnPuTyCWPnY8R1TLGBYUJTgqu1JdL5zHQcdKTavyn9s3uOKUGi1W6nmZly55o/ISTTnpTBbNZAEBmrpeBrkmt+i50EbdcXwVK218VWXXuvKoKleUfq8yBRZeqwlloY1w0+0TdbkMLiss3DhTp5suK5KFLJGxSUE8vyvLg4Hqc/X6W2U8f52W5xlGwTLt9p8qb5/VY1elreReuQepgCiFjBWYJab14KnEW7Rn/ocCC1oCjbMUId0qE0ZVC/bCsp+96hNCWPkr2F4zVw3Mx/MLdiz5GXeJzc/Pt/9j7N1eanh9+S3HiGaNsfKzounJ1AFMHxNpKa8Fo1AzZXRi4MOD2m7v37//5ZZmovmkOfWqd6i7XLnjxIkT9off+18200cXr/ishSZpx9p81/24pn1CWGTLqCqLjS1zDlYUE67rXFXqwdreG8IsuUEozJ18RnFtBxikfaszrlG2+SRX9rfaf8CN+OYvLqHbJ1d9mZ/xtfhel5dYfrpjvJ+Ucugki+9SAB4soNzKhUkHy39u3+BKJuetmGWGhQv0hsDKs4gapuCYIAisrvt2LjRezwKCmkNLv3KzAyXJxmzmA0y05YKUSIIqObx0Q7SeZIWZvzCNcTDYUNUWHHOum8jUOn0l36/Gy+AnBQWZU3T6r0N5/iEDL7A8xnV4Lyh41us52VP/s9nKHNrydKCuXROFYk6QIGM4SB7uZP0kL39F5e2zeuxKVgpR1VpQAhW2NJNVWaHAStBaDuxf9cFuvH9A676jCrWhfGXCqDp7+mnmnen0JbcEqFaujhw5YoN0OYrUcvztQoUFVOXmv2WetYw4TuBycnKkzz//PNuz6Ezd46rYze5+qy8X1fJdJsjlVxXeuA4LpRUj3nY8QPfHf5DkAWFVvlFksw+klVc20PZFrirTQuM6j5zDOD6gyDXgYG0hkLtp5BwQWCNY7aD2uTrw3WGW0PmqKISUeniTS1w5/v7ftDNMGTCAu2HYD2VHvPK2iK83f8lLz12jXAXIxAxJ5FiBPKQl12Nyta/0n8drGmMXZACzpdd53x4UFcyUmkBHlKgy3X+imCPt+/p5ce0zx4QXD73GNIbBpckrln76E3HVpFX88JXhTKXrW+W3lgn4fGIVBFaNl8GpOdnvzjMYeuO+LdG8nIk8d+/U4OAOu83ml+bm5Pzmfm0jmUw1Xqeb3FQuHxYFitxYJMrZOZtt/vt5uams5oY5FONKVoIkz9a0qESY3cjnHUvjVY0qrMfs53dt3brVMVtAERHfulDwPHyl4MWCkFM/H2Te6acvaURe4+py/rwXbEHy+mDlGuUqIPH6UYXGZvLSulGFoNARNpXuPWbKsXdvn7TjQIGuY1VeSCVIpo5m86lvV/qFXVXYQuOHLR/KNEHdmB70qOB8HDy2m7rxj3w6XFz28Ce1ILBqnyuZQsHM2UXbuLhgymUMB7OXKFPSminHucY3zmDhSVOvElk2yxHpx9de9GI5rFGuAqW8s4wPZ6mqyIe5lv0eru6XuSQUrRWlE3NO1HXfLsmVPIgrjglCJYogzgI08ZIgqBwRUFuh4FgYvWR3YkHmOnHVk6vZmd0mcefCWVyPSYlgk/FVe2s5k6wFOZXks1bK4OqCguzbAgLG3KXRrNCAO04CbvV2e5xBED5rrVSezxHFgzZJylBxXFKoILSMlsnkDeCaQOeyIbmSlP1EZuZSVrNjSItxJStBWLWF+C5HpvgLOw7xxl4VXXcmNetypvEhsiMnmRiUaRHCPblHfID5wA/ffVN9q/06jOFyJVQaP17h6vI/jzeWlfHWykq1xJXMEB0ileHM7EHRCnlMK431v505dxf++NELLZqvr8qrWa1Wy4qVXx7yC7uq6NH6PNtMMjZ8ngUanaMenMBjHYgs0fIs1+e5XdKPsw7XTDuw7nAF4mE8wzGy7pEJu4VxAfrbIOetVwUl5nRdyb+wN4QFx0y8YkyF+8X5/R9i5/aZ/IWrxiz59318wjAWEsMcyTvhALFR7v7fd9Z1rnIuZEGjJKdyvpvDGfBKptYVKaqAQO1VPRI282Fp2/tzQFw51kuRfp6TzBp3mskldHkPGpeVXz7fbjnNzu4+5ytl8LFLl/Yznn/oTo1mvozjwqPA54dDe6dQFKPyJSkK9xtUwnOiqJI7V313lEFIWTabfkpw8MLn0tNHHbVYTLXhr0pGsKo93Bd2bN1mfWLL8VlWwVjedaeYYRj30Mf57MKh7SGms7sL1MrgDC7YI4HVTDz54z9mc/VFaIpv2liWcvdKaFSSRE6qIMQcrLBfjFNd3vDSgUN58tYWkQ8oW195KYJVS1w5VnIvM9InMEOQXpYClz0xYQK2fq91BXuft6tyEdsugDW/dS7TGuVME3x1FweuOm0zy1nzW95h+9YMYBePmLz+TLXNVUzbQK5Z784sqtmDUlDEjQ5e3O0NBzNrDQO4hxer2LkD30g7l/zOzHmXB+A6ohKu6+1WxvIvpYG4MvtTGbT98fmfIT27XMiwCJHeMoM4tfXI7x8tOlnny2DK4Rxmzj/CFAFtKrxWtGezwuwt7OK/GxkncOzvNaccEayjW5dyQQ02gOAysLDEJ5kk5ktHfp4hbfuwWBeX9PHA7dzkX95iYfGjmaCo3DZg1sJD0vYFHm05U1f81WOpqQcGaLV3zDQaJ4UKwn048B0FVXnqEpveEXI5s3Fcp9dCQ5e/np4+8m+zuaCm/ZWsWiuQUvDJxwtT7/1o5Oov0qNGl/t8hlglKNVJLDx+0qY0XBjNAi1nzwpg2IGvf/S4mqyakK6aaq9ykLH8WzwSdm5ZB/uRPe7n3udufOz3XH3vsgmuqUkUNcSVYyk3rvzv8QG6PtqIxbatUhchs1kKpJ3Lf2bn9hf4hV2V9RB3TH0eBEQjpgstYwVyOBdowA2NE7h7Z70ozb/n5WuSqnWUK+7WyTcyXXgPptS2ZWp9O6YNxbE1zPFZco9GXOfI0BCFVj8WGNaPi2mXy0w5+5kl7y+WdX6TNP+u97kxqwpYSNxYJlOomN3cjev+eIK09cNj/lIGv/vuu5x7+s/433eZUSO9dY+eqhNfLz52zFrXuZL2fJXJrh+0kenD7i//QhHLkY6Zs9uwo1vnST+/e+byVytG/S3JFPu5CRueY4WZWpaf/g8kIzdwzt3SmT2/s10rU7i+z7dkmpDGUtoRGVOojjNDbHQlZiiK7MLBNcxuka6h9NaKv1qdl5cN6ZWRQUEfPqzXd42QydqByGoGbp63SlJGjige/ddi+T3Tbs+6JzBwGZwPVGPbsWgmYftpRuPn72dkPLK1oCC7Jv2V+yxCr6hRs9nMog9+9kVU46d6nTfJG5f9OKA5DXFFyeM6VrL3D/hvxfvz53s2TbiSQ6EcawAVXyfM+xEsTqpwDNamzVsPzFn01P5iUbyZO1OYJohVILAqEdKt41xxnFhepI8ryLI57nnDA6sktV5bpXuIdibThS21fTxktq/bVZlP89CH/Zg+fBAIC1bm8gIOT6FgjmvslkHc4Pe2Sl8+ublqBl4HuWrSTc91Hj6PqYM7OrpDsZsU5+XIKpispQIXrkKfFcOY1RwIAqszy02FdGk8F3/TZmnVlGe4zo/sZa36LWdBkXLWut8XXGjcJyz54Gbpt08P+4O/anXq2xU7wsb1uWSVN6juvOMDzAdt2xdv8BXfLq19aRf35Ma/mELdrtzYilLNMZO8EWvWcyY7sXMsO7kr7/KTPTD/ASaTPwh1AM/UgZ1Yow6dHA+rDXlc2rXyIku6eQCTq4Y4xp6qNHBTe9HyHx5Vxnm/SkuHbi9/C4y67a+WZGVdgrQGDteU6bY5bsRAnW4piiyVS2TxfMsnDYZPFTw/YmNeXkZN+StZTZDy1ltvXZi36rb3nr/Qekae3YOVkT3EveFZ3yR/M3e9d55aqqUd4So2V7PVdtVaIHa7Vaq9GEjNcxWnNh/KsnGlDvwIV1hPW84fcYxZuO/62LVHTNqEqtxD4JjtusiUvYv9xa5KmlmXEQ1Yg5YzmM5Y5KwrAl6De+7Ftp3FdXlkgLRj2Tmft6vYdgFc3+cWAwetWVAD3Bi3CkQKRV2GmPQRILZMjGWe68nd9uxK6ffPH+EadfwWRNsgFtlUzzTBE5gxfgKX1COXmbL/ZOlnFkub3tnjq3Y1Y8aM5Ge+un3ZnJSEF0SPN2+sGDhxaaj20OJpy5dn+IxdXThkZid/n8eSun+E07bLbqzIixororUj12fKRGnhfY59dLk7prZlEQnjwYaULMDZVR8cjV3MJpZxxuT4WxNsAvup/EKloi2V/fbJayCyRF/1V55i1Pnz+2U8/9g9RSIrAEt0TJHIajbeYPhMyXHD/i8391JN2JWspl560SsTtz796qfz30yOfaLAzgVea37dg/M2tjq6YsnLq1blVF691GWLAQFcQeEp1tvnnJ2B58r7XdXUV93laqzs1492h3W5+GeOJsn9fCO1Jfle1X8/D01Pd4jQFodXLLsrISHEnSuPfRLg8/9bcdI/7KoUm+g09HWmCQmE5LnDxo1j7RY96/TwDLZj2Yiq2nhd4Yq746UBLDS2teO9BEX1ZIprIYXGMZajbsL1ePxRdu7vzaz5rYMc47gwRTRBERbIci72ZJnJPbnIJrOkT8cs81W7Ov71m+sGD5rVeGWK4aHqyA97JsZEpizf9N4rW33NrqSFA3dwL+9+nxkbTyr3QiXYSBBukWp/kBv0zl5p/w+7WJPOT4Mdhjp6IlwbaDu2V4IqLjfF7jjOSxNZcBQuVls5cXXox8nS2qknfdlflf9P7+7bJTbi3Lm/FLGxj/YHkYVTCVyRLIHnE0YbDJ8reX7Yt9nZF71tVzUmsA4cOGButHTamtmjXzJPO9NwdLpNHlXVwjcwPPvbHpfWfz526tQzVVKZdd5YKvM6UtV+5+NcTRw3+p8JEyakP9OmTbE1rpJPJmc/8957Z11/T3vlFTw+WwOu1bcc0qA57cBR38jU+ivO3CPb5Iu60GSKzuz+N1uzr5/Z78tcSaEN2ztEj0xZvRljlyrmq1B1ZBtmL2AtepWIeEEFaWzMHOI2pMFz7M6Xf2f/9+phX7SrVdDIndqixZLhbYaJn10Ivt8mcVUmEyNXExqkLS/4cf6KHTt2FPqiXUlvdv+IPb9DyQxxY1h5c8JxQ3VtqIxFt3wcbOAmSWu4vkjoy0r6eAWLbPYsG7XyoqTUNHG8p6cNIqv5H7b765fYygmHfNpfVaYedFaEQ86c2fNFXNxjd+h0H6PIUgBnMQoFjslq9GxY2MpDZvPth0wmkzftSlaTHKxbty4nIyNj7aIXZ6S/k5E04I8sdVc74+Se/j5SaT01MTr1W+ufq3+smrjyESVelX2qKvqdxPkVTWazWcKuZzi8UHHh4BihBKKahTJ9eNV+ixEaTDFtcPbYfp/mQakOcXTZeMNEcA1cydaI7V2TzYbOz2ByVchV17iiFU263Ah/HfZVGrGr8LnnLEund3kg5e3k6IczrUKljQu79l+JO7d877cLNn788ceXfNamsBvulbZz2eQfj7AGrUYxhbpFmddqQ7BbOpHhbjAYQS3ZRY0+XRfKM7W2GRPtzRzjJN2XUSlbWB1hGWdWgbD6mh3/vZD5JSr27Q+cPr1rVaNG43rrdPNRZKHgiRMEXMYhJFahkHsmsK6hnVWlivwa1pXBVsnhIfdtnj1rVvL4ptdtW3Ix7KaD+aqmFy3yUke3BwhSbqLadKh3SM7eHvyx3QsXLNqPQs1nxFJlufJkyCBXhd9xfsiVJ1xKfiiuqoOrj4ZsZo8uG82M8e2ZTKGvVBRcEq0s89w+NqfPjz7PVUBwoCPa5BXvqsQUwIyN5SCisuFZQkp/Bj1O7mng63Y1a9as8/37H/r62wkTTizITOi5IV3Xy5Mxt8Fy+8V7QzN/vC/g2LZXX31tT+UjV3WUq3f6bGAdB//Buo24EcpZd6bStmK8LJRx/BWDcwxWr2DEDF6jCCivPBYwuzWD2W2XWH76XpZyZA87uPEI+2XxJb/xV9fg2+89eXLnuvj48T0DAxfAL+TwJKaNOTljN+Tk5Hr91eHlR8LHWXha3I4A93Cz1xTvrVu3Vo4ZPTouPiEh/JIqMvZEoTzojFkZlG4RNO0CC5KVHLPdFHDp1NmzZ1O2btuWvGjRopo2GByoiJ3duISzc0C1d7l69NFHDaMee6xLedfMfOONLThF2v3cvA8+SOzYsWPzciI+BV27ddvkT1zVSsEmrogr4qpCvDFzZlyXLl2arMsOb/lHrjYhxyYEJpsFh4jkOWaPVNgvGOS2rO7BuUe6KC4c3vDjj4dnz559geyK7MpbXK2Nj+98g0YzZHte3rL7TpzYVRNcFQksjp2F1mvtkQVo3769KjExURkXFxcQEhys/GvfvkyTySSVFBKVxzV1EV1tWHWAK++BuCKuiCviqvowevTo0Os7dAjVaDTKsLAwRzTLZrOJGRkZOZmZmYW/bN9+8csvv8wmrsiu/JErFFg4EwgHAWN0qMD/yLpmNYqx2dAryp24Iq6IK+KKuCKuiCviqnyucAyW6JRsktsxoQgluWHEFXFFXBFXxBVxRVwRVxVxJStBllR5sjh/5rc0Togr4oq4Iq6IK+KKuCKuyuWKrxpBJfOrIqpzghdXY6QRV8QVcUVcEVfEFXFFXJXLlauL0JWukbia47ncvCo1w6BcNS1d5objRGeexBVxRVwRV8QVcUVcEVflclVyDFbNklVtMrTEI1dq+qbkmWKXJLF6VTxxRVwRV8QVcUVcEVf+ylXJCJYPDljz6uOW5IYRV8QVcUVcEVfEFXFFXFXEFQosuzO5wn8e3r2GBqrVyG3KvAnnJMrFESOuiCviirgirogr4oq4qogrFFi2y4qriCgPH00q41w1jxyTaoJJyRNFaiv2N3FFXBFXxBVxRVwRV8RVGVy5BJbtsiIt9iyVXY6+pvd9k8ohsFqIlJy82NwMi7girogr4oq4Iq6IK+KqXK7cBVaJvlTJR5eqkCpWmJUzArEUwyKuiCviirgirogr4oq4KpMrFFgWN8Ul1p6yrEk+K2UFLqVucf5NXBFXxBVxRVwRV8QVcVUuV+6D3H1wuqWHuKbIHzLLlRzcR1wRV8QVcUVcEVfEFXFVJlflj8GqUw/tyqOyfbzsGge9cZ71PRNXxBVxRVwRV8QVcUVcuXURllxotJw78qy2VsgvJg6r9V9N8uSpS9vkkrgirogr4oq4Iq6IK+KqVK5K2yrHi1KyrqBS71HWAmvEFXFFXBFXxBVxRVwRV6Vy5eoitBcnrw4SU9lHqpZXcGTCsSsD+hhxRVwRV8QVcUVcEVfEVUVcyZj75oSXs5fqHjtSJVmolleQSlPqxBVxRVwRV8QVcUVcEVflciVzU6J1bEaA5E0WKvPv5RKgdjfDIq6IK+KKuCKuiCviirgqkyv3LkI7q+sdpjUdhZQu/79kaJS4Iq6IK+KKuCKuiCviqkyufGMdLNc0S8n9LbgK3rJaFz3znfU/iCviirgirogr4oq4qnWuQGBxVsi8gnBfVWSgN6Ujd43fVxrIj9X5TsQVcUVcEVfEFXFFXBFX5XIFAksCwi53E5aj7iqLaiSq9jWyrciwJEZcEVfEFXFFXBFXxBVxVRFXsiLCqqMv9RrUZ4UrrdY6W3YnT4y4Iq6IK+KKuCKuiCviqiKuSo7Bqh3JWIyoOrk4WWl9z8QVcUVcEVfEFXFFXBFXpXLlmkUo1p0nrORjVGWfocpDZFdmTxBXxBVxRVwRV8QVcUVclcuV+1Y5NUtWdYlOryrZyzMLSm4RQFwRV8QVcUVcEVfEFXFVJlclN3uuamZeF51FXEjOVeirM9OK/kWLKVJGXBFXxBVxRVwRV8QVcVURV9cosKp9amMFBNfw/YrjGg2LuCKuiCviirgiroir+sLVNQqs8kiUPDh3Lfn5mmERV8QVcUVcEVfEFXFVX7hy34uwOmWjh+euJb+a1cGs+B5MxBVxRVwRV8QVcUVcEVdlcsUXJ4pjdR6194gicUVcEVfEFXFFXBFXxJUnXP2/AAMA0irEt+vK6nEAAAAASUVORK5CYII=";
		var buttonsImg	= "iVBORw0KGgoAAAANSUhEUgAAAGQAAAAUCAIAAAD0og/CAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAABgZJREFUeNrkWN1PXEUUv3Nn5u4uWwoslGIJYKHyYUuEhLL0K4FGpQkxMZr0zXc1vhj70tbEGGP0H9A3E30wMdGkaVPsiyiVgtCS+FGEpeUjLSKI7HbZXZa9u/fD370Dmw2aey+tBpOebG7mzpyZe+Y35/zOmSX9V69Kuy3r6XQ8Hq+zRVGUQCCAzo2NjWw2e8+WK+nWn7PVu24n293Pm6aZSCQoY729vWgDoFQqBeAsyxjjnDc1NTU3N5eMjlb+kfxOfUoz6WMKlqbrqWSyvqGhtrYWkKmqCrzQTwjBU7cFnT6f7+TJk7X377PxyA9qfdwIPI5gAanDR46EQiG4kqZpxJa/qyEYoVBdXf06wnNo7trG4f81WDhwwxY0sB9ZlkWneC1sy7b84563SSKZ3F9VVVlZuba2hrmUUmcD1tfXoXy2ZTX26/yYetDNYgMWS4YmmTqaljlElmRGhOX2kPW0vNgeohy2Ww1Hy72ClcvlEBGIC2aLgE9sEtBotqCNkAFDu4KFieCmnp6eZDKJtkDfdQrwamlp6Z3/elyt0yXZESvDzGXM7LqpZfFmYSJTifkI81nDumqNmpv9hHECRJnf9Yg9gQVcMplMuKuroaFhbHR0cnISnV3HjtXX1w8MDMSi0cbGxs5weHZ2FqOA0nXzIHLMFd7q7FPb8MLKmNjyy/JE7oCjxZqppiYvtJUU8Xzf+/0zH4+sAqDzzz7xRk9tofqrX97rn8lJ1gE4e5aHkIEL5TTQsY52RlURQa2trTjkoaGhWCymGwZGBSWjAWXXNbEIOAj63pESAgfHxGfuTCdYhYOaLmdyapJYPiWdOP9VckP74q3nL/Ydmry3EllKBaUy9J/7bOTbO2vUXyxzH361RT4iSy5h6CUEEFaClcRrVVXV6dOnJyYm5ubmUBPB6Qw7/guZy3XPJSUleO4ULEhpaWmlvOajxBEs4KSJNpcJI+ZiNPV0TSgUYFwyiGRZSyUT4ccBAKP2z6baRwdL0HYeuDNnzqBQHB4eLisrA0mJRFao6bomfEpM3ClY+JDf7w9IKncEi1DCt9IMlaUjdaGupqpbd1d+vB8HSVB7ADYCHwbKAlKcESpbHO/MWd7BEh/v7OyEucjlgkFEvxjKZ0OP3gqk8t7qHSyLFiTiCpa+pTDw3st4Rn6LvfnpMC/aK5mmAPGDV04Ihe/vxD78Zlm2ciX518AS7fHxcRAW7iUdHR2RSES4xk49C0kA1RMKdBG/3gUrIymrxO8Klra18753Lx0IBc+9dPTa232vfTK69GBDtrnsnc9HbswllT2lzFekKH7bs4gXHNylsGJEBsQTYKHyRl4TxC8gK3QuB0EMorwCWHSHgimYmJT3AiznH9tCEyDMLMWv3potDigvtB+gki72IVsxCGcxGTGoqYHXuCy5rOnFs4SVQhPPlZWVkZGR48ePh8Ph1dXVdDot/AtDYv+uaxYXFy8sLCCv7TQMsT4mxnmlq2cpCiebxktoHz20H+20qiucCWttpqIMBalkyMQAWIRK5NEJXlSbiB20kf7Ky8tB8Hjiltvd3T04OIg9iOCCmhewkAqnp6fb2tqg7z0SsROEIFJwfM9z3DleGDV9fpHaLl14UXQOR5b7b/8ZCBYzruD14tlwXn909sFHN1YoMHY0nCCpeSlKQTEoEQoreNiNfuCC13x5Ce5HBe/lAOCSwWDw1KlTWNOLf4mEgMpu8He+7K93MVjX9Gwml1nXc1nJrvvADpQplPvQNrSslrUqePuqg6KBW0OKHztxTohe6yy4ANynsIyCixmb1yuSV/N+N8RFb3FxESkCxa24OTkbgGWnpqbGFrXVYLPrtQMRxeSAZbCBkxBGWmhZlx7rMuQ3A0WGkafazSFrX85h6GVjXurMh5B9+/aNjY3BQ9vb20VN61AS/2RLtKybycTD2tTiKu4QrL6HMJjcvHlzF/+lQQwuLS2hlAf3VVRUbINMHCQC9vr163czpbE9jbrMd/PPPy+e9R9+nrGamppoNHr58uWDtoD7BWrAKJFIgM7n5+evpFsbnqyzM9duyl8CDABOPvGfmM8FbAAAAABJRU5ErkJggg==";
		
		// Create the settings button
		$('<div id="ext_settings_button"><img src="data:image/png;base64,'+iconImg+'" alt=""></div>').appendTo('body');
		
		// Create the hiding overlay
		$('<div id="ext_settings_hide_overlay"></div>').appendTo('body');
		
		// Create click event for settings pane
		$('#ext_settings_button').click(function() {
			
			if($('#ext_settings_wrapper').hasClass('opened')) {
				cp.hide();
			} else {
				cp.show();
			}
		});
		
		// Inject the html code
		var html = '';
		
		html += '<div id="ext_settings_wrapper">';
			html += '<ul id="ext_settings_header">';
				html += '<li>Névjegy</li>';
				html += '<li>Főoldal</li>';
				html += '<li>Topik</li>';
				html += '<li>Egyéb</li>';
				html += '<li>Profilok</li>';
				html += '<li>Tiltólista</li>';
				html += '<li>Sync</li>';
				html += '<li>Logger</li>';
				html += '<li class="clear"></li>';
			html += '</ul>';
			
			html += '<div class="settings_page">';
				html += '<h3>SG Fórum+</h3>';
				html += '<p>Verzió: 2.6.0<br></p>';
				html += '<p>Kiadás dátuma: 2012. 03. 07.</p>';
				html += '<p>Fejlesztő: Gera János "dzsani" <a href="http://kreaturamedia.com" target="_blank">http://kreaturamedia.com</a></p>';
				html += '<p>Közreműködők: Viszt Péter "passatgt" <a href="http://visztpeter.me" target="_blank">http://visztpeter.me</a>, Krupa György "pyro" <a href="http://kreaturamedia.com" target="_blank">http://kreaturamedia.com</a></p>';
			html += '</div>';
			
			html += '<div class="settings_page">';
				html += '<div>';
					html += '<h3>Chat elrejtése</h3>';
					html += '<p>Ezzel az opcióval a fórum főoldalon levő közös chatet tüntethted el maradéktalanul.</p>';
					html += '<div class="button" id="chat_hide"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Csak olvasatlan üzenttel rendelkező kedvencek mutatása</h3>';
					html += '<p class="sub">';
						html += '<label><input type="checkbox" id="fav_show_only_unreaded_remember"> Utolsó állapot megjegyzése</label><br>';
					html += '</p>';
					html += '<p>A fórum főoldalán található kedvencek listában csak az olvasatlan üzenettel rendelkező topikok lesznek listázva. A bővítmény létrehoz tovább egy kapcsolót a kedvencek cím mellett mellyel könnyen visszaválthatsz a régi nézetre.</p>';
					html += '<div class="button" id="fav_show_only_unreaded"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Rövid kommentjelzők</h3>';
					html += '<p>A főoldali kedvencek listában nem jelenik meg helyet foglalva új sorban az "N új üzeneted érkezett" szöveg, ehelyett helytakarékos módon csak egy piros szám jelzi az új üzeneteket a topik neve mellett.</p>';
					html += '<div class="button" id="short_comment_marker"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Fórumkategóriák kiemelése</h3>';
					html += '<p>A fórum főoldalon átalakított, átdizájnolt listákat láthatsz, mely jobban kiemeli többek között a kedvenceknél a fórumkategóriákat is.</p>';
					html += '<div class="button" id="highlight_forum_categories"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Blokkok átrendezése, rejtése</h3>';
					html += '<p class="sub">';
						html += '<label><input type="checkbox" id="hide_blocks_buttons"> Átrendező gombok elrejtése</label><br>';
						html += '<button type="button" id="reset_blocks_config">Alapbeállítások visszaállítása</button>';
					html += '</p>';
					html += '<p>A fórum főoldal oldalsávjain található blokkok tetszőleges átrendezése, rejtése.</p>';
					html += '<div class="button" id="custom_blocks"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Üzenetközpont (BÉTA)</h3>';
					html += '<p>Saját üzenetek naplózása, azokra érkező válaszok nyomkövetése.</p>';
					html += '<div class="button" id="message_center"></div>';
				html += '</div>';
			html += '</div>';

			html += '<div class="settings_page">';
				html += '<div>';
					html += '<h3>Ugrás az utolsó üzenethez</h3>';
					html += '<p>Az "ugrás az utolsó olvasatlan üzenethez" több oldalon keresztül is működik, egy topikba lépve automatikusan az utolsó üzenethez görget.</p>';
					html += '<div class="button" id="jump_unreaded_messages"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Következő oldal betöltése a lap aljára érve</h3>';
					html += '<p>A lap aljára görgetve a bővítmény a háttérben betölti a következő oldal tartalmát, majd megjeleníti az új kommenteket oldalfrissítés vagy lapozás nélkül.</p>';
					html += '<div class="button" id="autoload_next_page"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Overlay kommentmező</h3>';
					html += '<p>Egy hozzászólásra válaszolva az oldal nem ugrik fel a felső textarához, ehelyett kiemeli a megválaszolandó kommentet és egy overlay szövegmező jelenik meg alatta.</p>';
					html += '<div class="button" id="overlay_reply_to"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Nekem érkező üzenetek kiemelése</h3>';
					html += '<p>Bármely topikban a neked címzett üzenetek mellé egy narancssárga nyíl kerül, ezzel jelezve hogy ezt az üzenetet neked szánták.</p>';
					html += '<div class="button" id="highlight_comments_for_me"></div>';
				html += '</div>';	
				html += '<div>';
					html += '<h3>Kommentek szálonkénti elrendezése</h3>';
					html += '<p>Bármely topikban a megkezdett beszélgetéseket szálonként átrendezi a script. Egy megválaszolt üzenet az eredeti üzenet alá kerül, ezzel jelezve és elkülönítve az egymásnak szánt üzeneteket.</p>';
					html += '<div class="button" id="threaded_comments"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Említett kommentek beidézése</h3>';
					html += '<p class="sub">';
						html += '<label><input type="checkbox" id="show_mentioned_comments_in_links"> Linkeken belüli keresés is</label>';
					html += '</p>';
					html += '<p>Bármely topikban egy beírt kommentazonosító detektálása, kattintásra az említett komment beidézése</p>';
					html += '<div class="button" id="show_mentioned_comments"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Smile lista csoportba rendezése</h3>';
					html += '<p>A smile lista egy legördülő menüben jelenik meg ahol típusuk szerint csoportokba vannak rendezve. Például: szomorú, vidám, stb.</p>';
					html += '<div class="button" id="group_smiles"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Topikba érkező új üzenetek automatikus kinyerése</h3>';
					html += '<p>Amíg egy topikban tartózkodsz, a bővítmény automatikusan kinyeri az olvasás ideje alatt érkező új üezenteket.</p>';
					html += '<div class="button" id="fetch_new_comments"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Navigációs gombok megjelenítése</h3>';
					html += '<p class="sub">';
						html += 'Gombok helye: ';
						html += '<select id="navigation_buttons_position">';
							html += '<option value="lefttop">Bal felül</option>';
							html += '<option value="leftcenter">Bal középen</option>';
							html += '<option value="leftbottom">Bal alul</option>';
							html += '<option value="righttop">Jobb felül</option>';
							html += '<option value="rightcenter">Jobb középen</option>';
							html += '<option value="rightbottom">Jobb alul</option>';
						html += '</select>';
					html += '</p>';
					html += '<p>Egy topikban vagy a cikkeknél gyors elérést biztosító funkciógombok</p>';
					html += '<div class="button" id="show_navigation_buttons"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Pontrendszer letiltása</h3>';
					html += '<p>Ez az opció eltávolítja a pontozó gombokat és minden rejtett hozzászólást láthatóvá tesz.</p>';
					html += '<div class="button" id="disable_point_system"></div>';
				html += '</div>';
				html += '<div>';
					html += '<h3>Hosszú kommentek oszloposítása</h3>';
					html += '<p>Meghatározott karakterszám felett a bővítmény oszlopokra bontja az üzeneteket a könnyebb olvashatóság miatt. </p>';
					html += '<div class="button" id="columnify_comments"></div>';
				html += '</div>';
			html += '</div>';

			html += '<div class="settings_page">';
				html += '<div>';
					html += '<h3>Reklámok blokkolása</h3>';
					html += '<p>Ezzel az opcióval eltávolítható az összes reklám az sg.hu-n.</p>';
					html += '<div class="button" id="remove_ads"></div>';
				html += '</div>';
			html += '</div>';

			html += '<div class="settings_page">';
				html += '<ul class="profiles">';
			    	html += '<li class="sample">';
			    		html += '<input type="hidden" name="color" class="color" value="ff4242,ffc9c9">';
			    		html += '<span class="color" style="background-color: #ff4242"></span>';
			    		html += '<input type="text" name="title" class="title" value="Profil elnevezése">';
			    		html += '<ul>';
			    			html += '<li style="background-color: #ffc9c9"><span>ff4242,ffc9c9</span></li>';
			    			html += '<li style="background-color: #f2c9ff"><span>d13eff,f2c9ff</span></li>';
			    			html += '<li style="background-color: #c6c6ff"><span>4242ff,c6c6ff</span></li>';
			    			html += '<li style="background-color: #c6e9ff"><span>4ebbff,c6e9ff</span></li>';
			    			html += '<li style="background-color: #d5ffc6"><span>6afe36,d5ffc6</span></li>';
			    			html += '<li style="background-color: #fdffc6"><span>f8ff34,fdffc6</span></li>';
			    			html += '<li style="background-color: #ffe7c6"><span>ffa428,ffe7c6</span></li>';
			    			html += '<li style="background-color: #e1e1e1"><span>a9a9a9,e1e1e1</span></li>';
			    		html += '</ul>';
			    		html += '<textarea name="users" class="users">Felhasználók</textarea>';
			    		html += '<p class="options">';
			    			html += 'Opciók:';
			    			html += '<label><input type="checkbox" name="background" class="background"> Hozzászólás hátterének kiemelése</label>';
			    		html += '</p>';
			    		html += '<p class="remove">eltávolít</p>';
			    	html += '</li>';
			    html += '</ul>';
			    html += '<button class="profile_save">Változások mentése</button>';
			    html += '<a href="#" class="new_profile">Új csoport hozzáadása</a>';
			html += '</div>';

			html += '<div class="settings_page">';
				html += '<ul id="ext_blocklist">';
					html += '<li id="ext_empty_blocklist">Jelenleg üres a tiltólistád</li>';
				html += '</ul>';
			html += '</div>';

			html += '<div class="settings_page sync">';
				
				html += '<div class="signup">';
					html += '<h3>Regisztráció</h3>';
					html += '<p class="desc">';
						html += 'A jelszavad visszafejthető módon, lokálisan is tárolódik! ';
						html += 'Ha publikus számítógépeken is használod a bővítményt, ';
						html += 'válassz egyedi jelszót, amit máshol nem használsz!';
					html += '</p>';
					html += '<form action="http://sgsync.dev.kreatura.hu/api_v2/signup/" method="post">';
						html += '<input type="text" name="nick" placeholder="Felhasználónév">';
						html += '<input type="password" name="pass" placeholder="Jelszó">';
						html += '<button type="submit">Regisztráció</button>';
					html += '</form>';
				html += '</div>';
				
				html += '<div class="login">';
					html += '<h3>Belépés</h3>';
					html += '<form action="http://sgsync.dev.kreatura.hu/api_v2/auth/" method="post">';
						html += '<input type="text" name="nick" placeholder="Felhasználónév">';
						html += '<input type="password" name="pass" placeholder="Jelszó">';
						html += '<button type="submit">Belépés</button>';
						
						html += '<div class="status">';
							if(dataStore['sync_auth_key'] != '') {
							html += '<div class="loggedin">&#10003;</div>';
							html += '<strong>Belépve mint: </strong>';
							html += '<span>'+dataStore['sync_nick']+'</span>';
							}
						html += '</div>';
					html += '</form>';
				html += '</div>';
				
				html += '<div class="log">';
					html += '<h3>Statisztika és lehetőségek</h3>';
					html += '<strong>Utolsó szinkronizálás: </strong>';
					if(dataStore['sync_last_sync'] == 0) { 
					html += '<span class="last_sync">Soha</span>';
					} else {
	
						var month = date('M', dataStore['sync_last_sync']);

						// Convert mounts names
						$.each([
							['Jan', 'január'],
							['Feb', 'február'],
							['Mar', 'március'],
							['Apr', 'április'],
							['May', 'május'],
							['Jun', 'június'],
							['Jul', 'július'],
							['Aug', 'augusztus'],
							['Sep', 'szeptember'],
							['Oct', 'október'],
							['Nov', 'november'],
							['Dec', 'december'],
			
						], function(index, item) {
							month = month.replace(item[0], item[1]);
						});						
					
					html += '<span class="last_sync">'+month+' '+date('d. -  H:i', dataStore['sync_last_sync'])+'</span>';
					}
					html += '<button class="sync">Szinkronizálás most</button>';
				html += '</div>';
			html += '</div>';

			html += '<div class="settings_page debugger">';
				html += '<h3>Debugger</h3>';
				html += '<textarea readonly="readonly">';
				
				if(dataStore['debugger_messages'] != '') {

					// Parse debugger messages
					var messages = JSON.parse(dataStore['debugger_messages']);	
		
					for(c = 0; c < messages.length; c++) {
						html += ""+messages[c]+"\r\n";
					}
				}
				
				html += '</textarea>';
				html += '<button>Clear</button>';
			html += '</div>';
			
		html += '</div>';
		
		// Append settings pane html to body
		$(html).appendTo('body');
		
		// Set header list backgrounds
		$('#ext_settings_header li').css({ 'background-image' : 'url(data:image/png;base64,'+iconsImg+')' });
		
		// Create tabs event
		$('#ext_settings_header li').click(function() {
			
			cp.tab( $(this).index() );
		});
		
		// Add buttons background image
		$('.settings_page .button').css({ 'background-image' : 'url(data:image/png;base64,'+buttonsImg+')' });
		
		// Get the requested page number
		var page  = typeof page == "undefined" ? 0 : page;
		
		// Select the right page
		cp.tab(page);
		
		// Set-up blocklist
		blocklist_cp.init();
		
		// Close when clicking away
		$('#ext_settings_hide_overlay').click(function() {
			cp.hide();
		});
		
		// Restore settings
		settings.restore();
		
		// Settings change event, saving
		$('.settings_page .button').click(function() {
			cp.button(this);
		});
		
		// Set checkboxes
		$('.settings_page input:checkbox').click(function() {
			settings.save(this);
		});


		// Set select boxes
		$('.settings_page select').change(function() {
			settings.select(this);
		});
		
		
		// Reset blocks config
		$('#reset_blocks_config').click(function() {
			opera.extension.postMessage({ name : "setSetting", key : 'blocks_config', val : '' });
		});

		// Init profiles settings
		profiles_cp.init();

		// Init sync settings
		window['sync_cp']['init']();

		// Init log
		log.init();
	},
	
	show : function() {
		
		// Set the overlay
		$('#ext_settings_hide_overlay').css({ display : 'block', opacity : 0 });
		$('#ext_settings_hide_overlay').animate({ opacity : 0.6 }, 200);
		
		// Get the viewport and panel dimensions
		var viewWidth	= $(window).width();
		var paneWidth	= $('#ext_settings_wrapper').width();
		var paneHeight	= $('#ext_settings_wrapper').height();
		var leftProp	= viewWidth / 2 - paneWidth / 2;

		// Apply calculated CSS settings to the panel
		$('#ext_settings_wrapper').css({ left : leftProp, top : '-'+(paneHeight+10)+'px' });
		
		// Reveal the panel
		$('#ext_settings_wrapper').delay(250).animate({ top : 10 }, 250);
		
		// Add 'opened' class
		$('#ext_settings_wrapper').addClass('opened');
		
	},
	
	hide : function() {
		
		// Get the settings pane height
		var paneHeight = $('#ext_settings_wrapper').height();
		
		// Hide the pane
		$('#ext_settings_wrapper').animate({ top : '-'+(paneHeight+10)+'px'}, 200, function() {
			
			// Hide the settings pane 
			$(this).css('top', -9000);
			
			// Restore the overlay
			$('#ext_settings_hide_overlay').animate({ opacity : 0 }, 100, function() {
				$(this).css('display', 'none');
			});
			
			// Remove 'opened' class
			$('#ext_settings_wrapper').removeClass('opened');
		});
	},
	
	tab : function(index) {
		
		// Set the current height to prevent resize
		$('#ext_settings_wrapper').css({ height : $('#ext_settings_wrapper').height() });
       
		// Hide all tab pages
		$('.settings_page').css('display', 'none');
       
		// Show the selected tab page
		$('.settings_page').eq(index).fadeIn(250);
       
		// Get new height of settings pane
		var newPaneHeight = $('#ext_settings_header').height() + $('.settings_page').eq(index).outerHeight();

		// Animate the resize
		$('#ext_settings_wrapper').stop().animate({ height : newPaneHeight }, 150, function() {
		
			// Set auto height
			$('#ext_settings_wrapper').css({ height : 'auto' });
		});
		
		// Remove all selected background in the header
		$('#ext_settings_header li').removeClass('on');
		
		// Add selected background to the selectad tab button
		$('#ext_settings_header li').eq(index).addClass('on');
	},
	
	button : function(ele) {

		if( $(ele).hasClass('on') ) {
			$(ele).attr('class', 'button off');
			
			settings.save(ele);
		} else {
		
			$(ele).attr('class', 'button on');
			
			settings.save(ele);
		}
	}
};


var blocklist_cp =  {
	
	init : function() {
		
		// Create user list
		blocklist_cp.list();
		
		// Create remove events
		$('#ext_blocklist a').live('click', function(e) {
			e.preventDefault();
			blocklist_cp.remove(this);
		})
	},
	
	list: function() {
		// If theres is no entry in dataStore
		if(typeof dataStore['block_list'] == "undefined") {
			return false;
		}
	
		// If the list is empty
		if(dataStore['block_list'] == '') {
			return false;
		}
	
		// Everything is OK, remove the default message
		$('#ext_blocklist').html('');
	
		// Fetch the userlist into an array
		var users = dataStore['block_list'].split(',').sort();
	
		// Iterate over, add users to the list
		for(c = 0; c < users.length; c++) {
			$('#ext_blocklist').append('<li><span>'+users[c]+'</span> <a href="#">töröl</a></li>');
		}
	},
	
	remove : function(el) {
		
		// Get username
		var user = $(el).prev().html();
				
		// Remove user from the list
		$(el).closest('li').remove();
		
		// Remove user from preferences
		opera.extension.postMessage({ name : "removeUserFromBlocklist", message : user });
		
		// Add default message to the list if it is now empty
		if($('#ext_blocklist li').length == 0) {
			$('<li id="ext_empty_blocklist">Jelenleg üres a tiltólistád</li>').appendTo('#ext_blocklist');
		}
		
		// Restore user comments
		blocklist.unblock(user);
	}
};

var settings = {
	
	restore : function() {

		// Restore settings for buttons
		$('.settings_page .button').each(function() {

			if(dataStore[ $(this).attr('id') ] == 'true') {
				$(this).attr('class', 'button on');
			
			} else {
				$(this).attr('class', 'button off');
			}
		});
		
		// Restore settings for checkboxes
		$('input:checkbox').each(function() {
			
			if(dataStore[ $(this).attr('id') ] == 'true') {
				$(this).attr('checked', true);
			} else {
				$(this).attr('checked', false);
			}
		});

		// Restore settings for select boxes
		$('.settings_page select').each(function() {
			
			$(this).find('option[value="'+dataStore[ $(this).attr('id') ]+'"]').attr('selected', true);
		});
	},
	
	save : function(ele) {
		
		if( $(ele).hasClass('on') || $(ele).attr('checked') == 'checked' || $(ele).attr('checked') == true) {
	
			// Save new settings ...
			opera.extension.postMessage({ name : "setSetting", key : $(ele).attr('id'), val : 'true' });
			
			// Set new value to dataStore var
			dataStore[$(ele).attr('id')] = 'true';
	
			// Sync new settings
			if(dataStore['sync_auth_key'] != '') {
				window['sync_cp']['save']('Settings Panel');
			}
			
			// Check for interactive action
			if( typeof window[$(ele).attr('id')].activated != 'undefined') {
				window[$(ele).attr('id')].activated();
			}
		
		} else {

			// Save new settings ...
			opera.extension.postMessage({ name : "setSetting", key : $(ele).attr('id'), val : 'false' });
			
			// Set new value to dataStore var
			dataStore[$(ele).attr('id')] = 'false';

			// Sync new settings
			if(dataStore['sync_auth_key'] != '') {
				window['sync_cp']['save']('Settings Panel');
			}

			// Check for interactive action
			if( typeof window[$(ele).attr('id')].disabled != 'undefined') {
				window[$(ele).attr('id')].disabled();
			}
		}
	},

	select : function(ele) {
		
		// Get the settings value
		var val = $(ele).find('option:selected').val();
		
		// Update in dataStore
		dataStore[ $(ele).attr('id') ] = val;

		// Sync new settings
		if(dataStore['sync_auth_key'] != '') {
			window['sync_cp']['save']('Settings Panel');
		}

		// Update in localStorage
		opera.extension.postMessage({ name : "setSetting", key : $(ele).attr('id'), val : val });
	}
};

var profiles_cp = {

	init : function() {
		
		// Add new profile group
		$('.settings_page a.new_profile').click(function(e) {
			e.preventDefault();
			profiles_cp.addGroup();
		});
		
		// Color select
		$('.settings_page .profiles li ul li').live('click', function() {
			profiles_cp.changeColor(this);
		});

		// Remove a group
		$('.settings_page .profiles li .remove').live('click', function() {
			profiles_cp.removeGroup(this);
		});
		
		// Save the settings
		$('.settings_page .profile_save').click(function(e) {
			
			// Prevent browsers default submission
			e.preventDefault();
			
			// Save the settings
			profiles_cp.save();
		});
		
		// Rebuild profiles
		profiles_cp.rebuildProfiles();
	},
	
	rebuildProfiles : function() {
		
		if(dataStore['profiles'] == '') {
			return false;
		}

		// Empty the list
		$('.settings_page .profiles > li:not(.sample)').remove();
		
		var profiles = JSON.parse(dataStore['profiles']);

		for(c = 0; c < profiles.length; c++) {
		
			// Get the clone elementent
			var clone = $('.settings_page .profiles li.sample').clone();
		
			// Get the target element
			var target = $('.settings_page .profiles');
			
			// Append the new group
			var content = $(clone).appendTo(target).removeClass('sample');
			
			// Re-set settings
			content.find('.color').val( profiles[c]['color'] );
			content.find('span.color').css('background-color', '#'+profiles[c]['color'][0]);
			content.find('.title').val( profiles[c]['title'] );
			content.find('.users').val( profiles[c]['users'] );
			
			// Re-set checkboxes
			if(profiles[c]['background']) {
				content.find('.background').attr('checked', true);
			}
		}
	},
	
	addGroup : function() {
		
		// Get the clone elementent
		var clone = $('.settings_page .profiles li.sample').clone();
		
		// Get the target element
		var target = $('.settings_page .profiles');
		
		// Append the new group
		$(clone).appendTo(target).removeClass('sample');
	},
	
	removeGroup : function(ele) {
		
		if(confirm('Biztos törlöd ezt a csoportot?')) {
		
			// Remove the group from DOM
			$(ele).closest('li').remove();
		}
	},
	
	changeColor : function(ele) {
		
		// Get selected color
		var color = $(ele).find('span').html().split(',');
		
		// Set the color indicator
		$(ele).parent().parent().find('span:first').css('background-color', '#'+color[0]);
		
		// Set the color input
		$(ele).parent().parent().find('input.color').val(color.join(','));
	},
	
	save : function() {
		
		// Var to store data
		var data = new Array();
		
		// Iterate over the groups
		$('.settings_page .profiles > li:not(.sample)').each(function(index) {
			
			// Create an new empty object for the group settings
			data[index] = {};
				
			// Prefs
			data[index]['color'] = $(this).find('.color').val().split(',');
			data[index]['title'] = $(this).find('.title').val();
			data[index]['users'] = $(this).find('.users').val().split(',');
			
			// Options
			if( $(this).find('.background').attr('checked') == true || $(this).find('.background').attr('checked') == 'checked') {
				data[index]['background'] = true;
			} else {
				data[index]['background'] = false;
			}
			

		});
		
		// Seriaize the form
		opera.extension.postMessage({ name : "setSetting", key : 'profiles', val : JSON.stringify(data) });

		// Save new settings in dataStore
		dataStore['profiles'] = JSON.stringify(data);
		
		// Save new settings in sync
		window['sync_cp']['save']('Settings Panel');

		// Saved indicator
		$('<p class="profile_status">&#10003;</p>').insertAfter( $('.settings_page .profile_save') );
			
		// Remove the idicator in 2 sec
		setTimeout(function() {
			$('.settings_page .profile_status').remove();
		}, 3000);
	}
};



window.sync_cp = {
	
	init : function() {
		
		// Signup
		$('.settings_page.sync .signup form').submit(function(e) {
			
			// Prevent borwsers default submisson
			e.preventDefault();
			
			// POST the data
			opera.extension.postMessage({ name : 'makeRequest', message : { url : $(this).attr('action'), params : $(this).serialize(), callback : ['sync_cp', 'signup'] } });
		});
		
		// Login
		$('.settings_page.sync .login form').submit(function(e) {
		
			// Prevent browsers default submission
			e.preventDefault();

			// POST the data
			opera.extension.postMessage({ name : 'makeRequest', message : { url : $(this).attr('action'), params : $(this).serialize(), callback : ['sync_cp', 'login'] } });
		});
		
		// Sync now button
		$('.settings_page.sync .log button.sync').click(function(e) {

			// Prevent browsers default submission
			e.preventDefault();
			
			// Get settings 
			window['sync_cp']['get']();
		});
		
		// Ping for settings chances
		setTimeout(function() {
			window['sync_cp']['ping']();
		}, 10000);
	},
	
	signup : function(data) {
		
		// Parse JSON data
		data = $.parseJSON(data);
		
		// Show the message
		alert(data.messages[0]);
		
		// On success
		if(data.errorCount == 0) {
			
			// Get the values
			var signup_nick = $('.settings_page.sync .signup input[name="nick"]');
			var signup_pass = $('.settings_page.sync .signup input[name="pass"]');
			
			
			// Store login credentials in localStorage
			opera.extension.postMessage({ name : "setSetting", key : 'sync_auth_key', val : data['auth_key'] });
			opera.extension.postMessage({ name : "setSetting", key : 'sync_nick', val : signup_nick.val() });

			// Store login credentials in dataStore
			dataStore['sync_auth_key'] = data['auth_key'];
			dataStore['sync_nick'] = signup_nick.val();

			// Empty status div
			$('.settings_page.sync .login .status').html('');
			
			// HTML to insert
			html  = '<div class="loggedin">&#10003;</div>';
			html += '<strong>Belépve mint: </strong>';
			html += '<span>'+signup_nick.val()+'</span>';
			
			// Insert new status
			$('.settings_page.sync .login .status').html(html);

			// Empty signup fields
			signup_nick.val('');
			signup_pass.val('');
			
			// Upload the config data after the signup process
			window['sync_cp']['save']('Sync Signup');
		}
	},
	
	login : function(data) {
		
		// Parse JSON data
		data = $.parseJSON(data);
		
		// Show error message if any
		if(data.errorCount > 0) {
					
			// Clear HTML from previous tries
			$('.settings_page.sync .login .status').html('');
					
			// HTML to append
			html = '<div class="loggedin error">X</div>';
			html += '<strong>Hiba: </strong>';
			html += '<span>'+data.messages[0]+'</span>';
					
			$(html).appendTo($('.settings_page.sync .login .status'));
				
		// Success
		} else {
			
			// Get the nick
			var login_nick = $('.settings_page.sync .login input[name="nick"]');
			
			// Clear HTML from previous tries
			$('.settings_page.sync .login .status').html('');
	
			html = '<div class="loggedin">&#10003;</div>';
			html += '<strong>Belépve mint: </strong>';
			html += '<span>'+login_nick.val()+'</span>';
			
			$(html).appendTo($('.settings_page.sync .login .status'));

			// Store login credentials in localStorage
			opera.extension.postMessage({ name : "setSetting", key : 'sync_auth_key', val : data['auth_key'] });
			opera.extension.postMessage({ name : "setSetting", key : 'sync_nick', val : login_nick.val() });

			
			// Store login credentials in dataStore
			dataStore['sync_nick'] = login_nick.val();
			dataStore['sync_auth_key'] = data['auth_key'];
			
			// Download the config
			window['sync_cp']['get']();
		}
	},
	
	
	ping : function() {

		// Exit when the user is not authenticated
		if(dataStore['sync_auth_key'] == '') {
			return;
		}

		// Get current timestamp
		var time = Math.round(new Date().getTime() / 1000)

		if(dataStore['sync_last_sync'] < time - 60*10) {
			opera.extension.postMessage({ name : 'makeRequest', message : { url : 'http://sgsync.dev.kreatura.hu/api_v2/ping/', params : $.param({ auth_key : dataStore['sync_auth_key'] }), callback : ['sync_cp', 'doPing'] } });
		}
	},
	
	doPing : function(data) {

		// Log the request
		log.add('Pinging sgsync.dev.kreatura.hu\r\n');

		// Parse JSON data
		data = $.parseJSON(data);
		
		// Update the latest data from sync
		if(data.date_m > dataStore['sync_last_sync']) {
			window['sync_cp']['get']();
		
		// There is no updates, 
		// Update the last checked date
		} else {
	
			// Get current timestamp
			var time = Math.round(new Date().getTime() / 1000)

			// Update the last sync time
			opera.extension.postMessage({ name : "setSetting", key : 'sync_last_sync', val : time });
		}
	},
	
	
	save : function(origin) {

		// Log the request
		log.add('Initiating sync (UP) to save changes', origin);

		// Make the request
		opera.extension.postMessage({ name : 'makeRequest', message : { url : 'http://sgsync.dev.kreatura.hu/api_v2/set/', params : $.param({ auth_key : dataStore['sync_auth_key'], data : JSON.stringify(dataStore) }), callback : ['sync_cp', 'doSave'] } });
	},

	doSave : function() {

		// Log the request
		log.add('Client data was sent successfully\r\n');
	},	
	
	get : function() {

		// Log the request
		log.add('Initiating sync (DOWN) to get changes');

		opera.extension.postMessage({ name : 'makeRequest', message : { url : 'http://sgsync.dev.kreatura.hu/api_v2/get/', params : $.param({ auth_key : dataStore['sync_auth_key'] }), callback : ['sync_cp', 'doGet'] } });
	},
	
	doGet : function(data) {
		
		// Parse JSON data
		data = $.parseJSON(data);
		
		if(data.errorCount > 0) {
		
			// Log the request
			log.add('Sync failed, authentication error\r\n');
			
			// Show the error message
		    alert('A szinkronizáció meghiúsult, ellenőrizd a felhasználóneved, jelszavad!');
		    return;
		}

		// Log the request
		log.add('Data received, processing...');
		
		// Get current timestamp
		var time = Math.round(new Date().getTime() / 1000)

		// Update the last sync time
		opera.extension.postMessage({ name : "setSetting", key : 'sync_last_sync', val : time });
		
		// Update data in dataStore object
		config = JSON.parse(data['settings']);
		
		// Update settings in localStorage
		for (var key in config) {

		    // Exclude some settings
		    if(key.match('sync') || key.match('debugger')) {
		    	continue;
		    }
			
			// Store in localStorage
		    opera.extension.postMessage({ name : "setSetting", key : key, val : config[key] });

		    // Store in dataStore
		    dataStore[key] = config[key];
		}

		// Log the request
		log.add('New profile settings has been saved');
		log.add('Updating the GUI...\r\n');

		// Update settings GUI
		settings.restore();
		blocklist_cp.list();
		profiles_cp.rebuildProfiles();
		
		// Update last sync date
		var month = date('M', time);

		// Convert mounts names
		$.each([
		    ['Jan', 'január'],
		    ['Feb', 'február'],
		    ['Mar', 'március'],
		    ['Apr', 'április'],
		    ['May', 'május'],
		    ['Jun', 'június'],
		    ['Jul', 'július'],
		    ['Aug', 'augusztus'],
		    ['Sep', 'szeptember'],
		    ['Oct', 'október'],
		    ['Nov', 'november'],
		    ['Dec', 'december'],
		
		], function(index, item) {
		    month = month.replace(item[0], item[1]);
		});						
		
		// Update last sync date
		$('.settings_page.sync .log .last_sync').html(''+month+' '+date('d. -  H:i', time)+'');

		// HTML for indicator
		html = '<div class="status">';
		html += '<div class="loggedin">&#10003;</div>';
		html += '</div>';
		
		// Insert HTML
		$(html).insertAfter( $('.settings_page.sync .log button') );
		
		// Remove the idicator in 2 sec
		setTimeout(function() {
		    $('.settings_page.sync .log .status').remove();
		}, 3000);	
	}
};

var log = {
	
	init : function() {
		
		// Clear event
		$('.settings_page.debugger button').click(function() {
			log.clear();
		});
	},
	
	add : function(message, origin) {

		// Get current timestamp
		var time = Math.round(new Date().getTime() / 1000)

		// Parse messages
		if(dataStore['debugger_messages'] != '') {
			var messages = JSON.parse(dataStore['debugger_messages']);
		
		} else {
			var messages = [];
		}
		
		var month = date('M', time);

		// Convert mounts names
		$.each([
		    ['Jan', 'január'],
		    ['Feb', 'február'],
		    ['Mar', 'március'],
		    ['Apr', 'április'],
		    ['May', 'május'],
		    ['Jun', 'június'],
		    ['Jul', 'július'],
		    ['Aug', 'augusztus'],
		    ['Sep', 'szeptember'],
		    ['Oct', 'október'],
		    ['Nov', 'november'],
		    ['Dec', 'december'],
		
		], function(index, item) {
		    month = month.replace(item[0], item[1]);
		});
		
		// Append timestamp
		message	= month + date('d. H:i - ', time) + message;

		// Append origin
		if(typeof origin != "undefined") {
			message = message + ' | Origin: ' + origin;
		}

		// Add new messages
		messages.push(message);
		
		if(messages.length > 100) {
			messages.splice(0, 1);
		}
		
		// Add to dataStore
		dataStore['debugger_messages'] = JSON.stringify(messages);
	
		// Store new settings
		opera.extension.postMessage({ name : "setSetting", key : 'debugger_messages', val : JSON.stringify(messages) });

		// Update the GUI
		var html = $('.settings_page.debugger textarea').html();
			
		$('.settings_page.debugger textarea').html( html + message + "\r\n" );
	},
	
	clear : function() {
	
		// Clear in localStorage
		opera.extension.postMessage({ name : "setSetting", key : 'debugger_messages', val : '' });
		
		// Clear in dataStore
		dataStore['debugger_messages'] = '';
		
		// Clear the debugger window
		$('.settings_page.debugger textarea').html('');
	}
};

